/* Generated by Yosys 0.9+4052 (git sha1 44520808, clang 10.0.0-4ubuntu1 -fPIC -Os) */

(* top =  1  *)
(* src = "Recirculador_sintetizado.v:1.1-78.10" *)
module Recirculador_sintetizado(clk, dataIn0, dataIn1, dataIn2, dataIn3, validIn0, validIn1, validIn2, validIn3, selector_IDLE, dataOut0, dataOut1, dataOut2, dataOut3, dataOut4, dataOut5, dataOut6, dataOut7, validOut0, validOut1, validOut2, validOut3, validOut4, validOut5, validOut6, validOut7);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  (* src = "Recirculador_sintetizado.v:2.8-2.11" *)
  input clk;
  (* src = "Recirculador_sintetizado.v:3.13-3.20" *)
  input [7:0] dataIn0;
  (* src = "Recirculador_sintetizado.v:4.13-4.20" *)
  input [7:0] dataIn1;
  (* src = "Recirculador_sintetizado.v:5.13-5.20" *)
  input [7:0] dataIn2;
  (* src = "Recirculador_sintetizado.v:6.13-6.20" *)
  input [7:0] dataIn3;
  (* src = "Recirculador_sintetizado.v:12.18-12.26" *)
  output [7:0] dataOut0;
  (* src = "Recirculador_sintetizado.v:13.21-13.29" *)
  output [7:0] dataOut1;
  (* src = "Recirculador_sintetizado.v:14.18-14.26" *)
  output [7:0] dataOut2;
  (* src = "Recirculador_sintetizado.v:15.21-15.29" *)
  output [7:0] dataOut3;
  (* src = "Recirculador_sintetizado.v:16.18-16.26" *)
  output [7:0] dataOut4;
  (* src = "Recirculador_sintetizado.v:17.21-17.29" *)
  output [7:0] dataOut5;
  (* src = "Recirculador_sintetizado.v:18.18-18.26" *)
  output [7:0] dataOut6;
  (* src = "Recirculador_sintetizado.v:19.21-19.29" *)
  output [7:0] dataOut7;
  (* src = "Recirculador_sintetizado.v:11.8-11.21" *)
  input selector_IDLE;
  (* src = "Recirculador_sintetizado.v:7.8-7.16" *)
  input validIn0;
  (* src = "Recirculador_sintetizado.v:8.11-8.19" *)
  input validIn1;
  (* src = "Recirculador_sintetizado.v:9.11-9.19" *)
  input validIn2;
  (* src = "Recirculador_sintetizado.v:10.11-10.19" *)
  input validIn3;
  (* src = "Recirculador_sintetizado.v:20.13-20.22" *)
  output validOut0;
  (* src = "Recirculador_sintetizado.v:21.13-21.22" *)
  output validOut1;
  (* src = "Recirculador_sintetizado.v:22.13-22.22" *)
  output validOut2;
  (* src = "Recirculador_sintetizado.v:23.13-23.22" *)
  output validOut3;
  (* src = "Recirculador_sintetizado.v:24.13-24.22" *)
  output validOut4;
  (* src = "Recirculador_sintetizado.v:25.13-25.22" *)
  output validOut5;
  (* src = "Recirculador_sintetizado.v:26.13-26.22" *)
  output validOut6;
  (* src = "Recirculador_sintetizado.v:27.13-27.22" *)
  output validOut7;
  NOT _217_ (
    .A(selector_IDLE),
    .Y(_072_)
  );
  NAND _218_ (
    .A(dataIn0[6]),
    .B(selector_IDLE),
    .Y(_073_)
  );
  NAND _219_ (
    .A(dataOut0[6]),
    .B(_072_),
    .Y(_074_)
  );
  NAND _220_ (
    .A(_073_),
    .B(_074_),
    .Y(_070_)
  );
  NAND _221_ (
    .A(selector_IDLE),
    .B(dataIn0[5]),
    .Y(_075_)
  );
  NAND _222_ (
    .A(_072_),
    .B(dataOut0[5]),
    .Y(_076_)
  );
  NAND _223_ (
    .A(_075_),
    .B(_076_),
    .Y(_069_)
  );
  NAND _224_ (
    .A(selector_IDLE),
    .B(dataIn0[4]),
    .Y(_077_)
  );
  NAND _225_ (
    .A(_072_),
    .B(dataOut0[4]),
    .Y(_078_)
  );
  NAND _226_ (
    .A(_077_),
    .B(_078_),
    .Y(_068_)
  );
  NAND _227_ (
    .A(selector_IDLE),
    .B(dataIn0[3]),
    .Y(_079_)
  );
  NAND _228_ (
    .A(_072_),
    .B(dataOut0[3]),
    .Y(_080_)
  );
  NAND _229_ (
    .A(_079_),
    .B(_080_),
    .Y(_067_)
  );
  NAND _230_ (
    .A(selector_IDLE),
    .B(dataIn0[2]),
    .Y(_081_)
  );
  NAND _231_ (
    .A(_072_),
    .B(dataOut0[2]),
    .Y(_082_)
  );
  NAND _232_ (
    .A(_081_),
    .B(_082_),
    .Y(_066_)
  );
  NAND _233_ (
    .A(selector_IDLE),
    .B(dataIn0[1]),
    .Y(_083_)
  );
  NAND _234_ (
    .A(_072_),
    .B(dataOut0[1]),
    .Y(_084_)
  );
  NAND _235_ (
    .A(_083_),
    .B(_084_),
    .Y(_065_)
  );
  NAND _236_ (
    .A(selector_IDLE),
    .B(dataIn0[0]),
    .Y(_085_)
  );
  NAND _237_ (
    .A(_072_),
    .B(dataOut0[0]),
    .Y(_086_)
  );
  NAND _238_ (
    .A(_085_),
    .B(_086_),
    .Y(_064_)
  );
  NAND _239_ (
    .A(selector_IDLE),
    .B(validOut6),
    .Y(_087_)
  );
  NAND _240_ (
    .A(_072_),
    .B(validIn2),
    .Y(_088_)
  );
  NAND _241_ (
    .A(_087_),
    .B(_088_),
    .Y(_063_)
  );
  NAND _242_ (
    .A(selector_IDLE),
    .B(validOut5),
    .Y(_089_)
  );
  NAND _243_ (
    .A(_072_),
    .B(validIn1),
    .Y(_090_)
  );
  NAND _244_ (
    .A(_089_),
    .B(_090_),
    .Y(_062_)
  );
  NAND _245_ (
    .A(selector_IDLE),
    .B(validOut4),
    .Y(_091_)
  );
  NAND _246_ (
    .A(_072_),
    .B(validIn0),
    .Y(_092_)
  );
  NAND _247_ (
    .A(_091_),
    .B(_092_),
    .Y(_061_)
  );
  NAND _248_ (
    .A(selector_IDLE),
    .B(validIn3),
    .Y(_093_)
  );
  NAND _249_ (
    .A(_072_),
    .B(validOut3),
    .Y(_094_)
  );
  NAND _250_ (
    .A(_093_),
    .B(_094_),
    .Y(_060_)
  );
  NAND _251_ (
    .A(selector_IDLE),
    .B(validIn2),
    .Y(_095_)
  );
  NAND _252_ (
    .A(_072_),
    .B(validOut2),
    .Y(_096_)
  );
  NAND _253_ (
    .A(_095_),
    .B(_096_),
    .Y(_059_)
  );
  NAND _254_ (
    .A(selector_IDLE),
    .B(validIn1),
    .Y(_097_)
  );
  NAND _255_ (
    .A(_072_),
    .B(validOut1),
    .Y(_098_)
  );
  NAND _256_ (
    .A(_097_),
    .B(_098_),
    .Y(_058_)
  );
  NAND _257_ (
    .A(selector_IDLE),
    .B(validIn0),
    .Y(_099_)
  );
  NAND _258_ (
    .A(_072_),
    .B(validOut0),
    .Y(_100_)
  );
  NAND _259_ (
    .A(_099_),
    .B(_100_),
    .Y(_057_)
  );
  NAND _260_ (
    .A(selector_IDLE),
    .B(dataOut7[7]),
    .Y(_101_)
  );
  NAND _261_ (
    .A(_072_),
    .B(dataIn3[7]),
    .Y(_102_)
  );
  NAND _262_ (
    .A(_101_),
    .B(_102_),
    .Y(_056_)
  );
  NAND _263_ (
    .A(selector_IDLE),
    .B(dataOut7[6]),
    .Y(_103_)
  );
  NAND _264_ (
    .A(_072_),
    .B(dataIn3[6]),
    .Y(_104_)
  );
  NAND _265_ (
    .A(_103_),
    .B(_104_),
    .Y(_055_)
  );
  NAND _266_ (
    .A(selector_IDLE),
    .B(dataOut7[5]),
    .Y(_105_)
  );
  NAND _267_ (
    .A(_072_),
    .B(dataIn3[5]),
    .Y(_106_)
  );
  NAND _268_ (
    .A(_105_),
    .B(_106_),
    .Y(_054_)
  );
  NAND _269_ (
    .A(selector_IDLE),
    .B(dataOut7[4]),
    .Y(_107_)
  );
  NAND _270_ (
    .A(_072_),
    .B(dataIn3[4]),
    .Y(_108_)
  );
  NAND _271_ (
    .A(_107_),
    .B(_108_),
    .Y(_053_)
  );
  NAND _272_ (
    .A(selector_IDLE),
    .B(dataOut7[3]),
    .Y(_109_)
  );
  NAND _273_ (
    .A(_072_),
    .B(dataIn3[3]),
    .Y(_110_)
  );
  NAND _274_ (
    .A(_109_),
    .B(_110_),
    .Y(_052_)
  );
  NAND _275_ (
    .A(selector_IDLE),
    .B(dataOut7[2]),
    .Y(_111_)
  );
  NAND _276_ (
    .A(_072_),
    .B(dataIn3[2]),
    .Y(_112_)
  );
  NAND _277_ (
    .A(_111_),
    .B(_112_),
    .Y(_051_)
  );
  NAND _278_ (
    .A(selector_IDLE),
    .B(dataOut7[1]),
    .Y(_113_)
  );
  NAND _279_ (
    .A(_072_),
    .B(dataIn3[1]),
    .Y(_114_)
  );
  NAND _280_ (
    .A(_113_),
    .B(_114_),
    .Y(_050_)
  );
  NAND _281_ (
    .A(selector_IDLE),
    .B(dataOut7[0]),
    .Y(_115_)
  );
  NAND _282_ (
    .A(_072_),
    .B(dataIn3[0]),
    .Y(_116_)
  );
  NAND _283_ (
    .A(_115_),
    .B(_116_),
    .Y(_049_)
  );
  NAND _284_ (
    .A(selector_IDLE),
    .B(dataOut6[7]),
    .Y(_117_)
  );
  NAND _285_ (
    .A(_072_),
    .B(dataIn2[7]),
    .Y(_118_)
  );
  NAND _286_ (
    .A(_117_),
    .B(_118_),
    .Y(_048_)
  );
  NAND _287_ (
    .A(selector_IDLE),
    .B(dataOut6[6]),
    .Y(_119_)
  );
  NAND _288_ (
    .A(_072_),
    .B(dataIn2[6]),
    .Y(_120_)
  );
  NAND _289_ (
    .A(_119_),
    .B(_120_),
    .Y(_047_)
  );
  NAND _290_ (
    .A(selector_IDLE),
    .B(dataOut6[5]),
    .Y(_121_)
  );
  NAND _291_ (
    .A(_072_),
    .B(dataIn2[5]),
    .Y(_122_)
  );
  NAND _292_ (
    .A(_121_),
    .B(_122_),
    .Y(_046_)
  );
  NAND _293_ (
    .A(selector_IDLE),
    .B(dataOut6[4]),
    .Y(_123_)
  );
  NAND _294_ (
    .A(_072_),
    .B(dataIn2[4]),
    .Y(_124_)
  );
  NAND _295_ (
    .A(_123_),
    .B(_124_),
    .Y(_045_)
  );
  NAND _296_ (
    .A(selector_IDLE),
    .B(dataOut6[3]),
    .Y(_125_)
  );
  NAND _297_ (
    .A(_072_),
    .B(dataIn2[3]),
    .Y(_126_)
  );
  NAND _298_ (
    .A(_125_),
    .B(_126_),
    .Y(_044_)
  );
  NAND _299_ (
    .A(selector_IDLE),
    .B(dataOut6[2]),
    .Y(_127_)
  );
  NAND _300_ (
    .A(_072_),
    .B(dataIn2[2]),
    .Y(_128_)
  );
  NAND _301_ (
    .A(_127_),
    .B(_128_),
    .Y(_043_)
  );
  NAND _302_ (
    .A(selector_IDLE),
    .B(dataOut6[1]),
    .Y(_129_)
  );
  NAND _303_ (
    .A(_072_),
    .B(dataIn2[1]),
    .Y(_130_)
  );
  NAND _304_ (
    .A(_129_),
    .B(_130_),
    .Y(_042_)
  );
  NAND _305_ (
    .A(selector_IDLE),
    .B(dataOut6[0]),
    .Y(_131_)
  );
  NAND _306_ (
    .A(_072_),
    .B(dataIn2[0]),
    .Y(_132_)
  );
  NAND _307_ (
    .A(_131_),
    .B(_132_),
    .Y(_041_)
  );
  NAND _308_ (
    .A(selector_IDLE),
    .B(dataOut5[7]),
    .Y(_133_)
  );
  NAND _309_ (
    .A(_072_),
    .B(dataIn1[7]),
    .Y(_134_)
  );
  NAND _310_ (
    .A(_133_),
    .B(_134_),
    .Y(_040_)
  );
  NAND _311_ (
    .A(selector_IDLE),
    .B(dataOut5[6]),
    .Y(_135_)
  );
  NAND _312_ (
    .A(_072_),
    .B(dataIn1[6]),
    .Y(_136_)
  );
  NAND _313_ (
    .A(_135_),
    .B(_136_),
    .Y(_039_)
  );
  NAND _314_ (
    .A(selector_IDLE),
    .B(dataOut5[5]),
    .Y(_137_)
  );
  NAND _315_ (
    .A(_072_),
    .B(dataIn1[5]),
    .Y(_138_)
  );
  NAND _316_ (
    .A(_137_),
    .B(_138_),
    .Y(_038_)
  );
  NAND _317_ (
    .A(selector_IDLE),
    .B(dataOut5[4]),
    .Y(_139_)
  );
  NAND _318_ (
    .A(_072_),
    .B(dataIn1[4]),
    .Y(_140_)
  );
  NAND _319_ (
    .A(_139_),
    .B(_140_),
    .Y(_037_)
  );
  NAND _320_ (
    .A(selector_IDLE),
    .B(dataOut5[3]),
    .Y(_141_)
  );
  NAND _321_ (
    .A(_072_),
    .B(dataIn1[3]),
    .Y(_142_)
  );
  NAND _322_ (
    .A(_141_),
    .B(_142_),
    .Y(_036_)
  );
  NAND _323_ (
    .A(selector_IDLE),
    .B(dataOut5[2]),
    .Y(_143_)
  );
  NAND _324_ (
    .A(_072_),
    .B(dataIn1[2]),
    .Y(_144_)
  );
  NAND _325_ (
    .A(_143_),
    .B(_144_),
    .Y(_035_)
  );
  NAND _326_ (
    .A(selector_IDLE),
    .B(dataOut5[1]),
    .Y(_145_)
  );
  NAND _327_ (
    .A(_072_),
    .B(dataIn1[1]),
    .Y(_146_)
  );
  NAND _328_ (
    .A(_145_),
    .B(_146_),
    .Y(_034_)
  );
  NAND _329_ (
    .A(selector_IDLE),
    .B(dataOut5[0]),
    .Y(_147_)
  );
  NAND _330_ (
    .A(_072_),
    .B(dataIn1[0]),
    .Y(_148_)
  );
  NAND _331_ (
    .A(_147_),
    .B(_148_),
    .Y(_033_)
  );
  NAND _332_ (
    .A(selector_IDLE),
    .B(dataOut4[7]),
    .Y(_149_)
  );
  NAND _333_ (
    .A(_072_),
    .B(dataIn0[7]),
    .Y(_150_)
  );
  NAND _334_ (
    .A(_149_),
    .B(_150_),
    .Y(_032_)
  );
  NAND _335_ (
    .A(selector_IDLE),
    .B(dataOut4[6]),
    .Y(_151_)
  );
  NAND _336_ (
    .A(dataIn0[6]),
    .B(_072_),
    .Y(_152_)
  );
  NAND _337_ (
    .A(_151_),
    .B(_152_),
    .Y(_031_)
  );
  NAND _338_ (
    .A(selector_IDLE),
    .B(dataOut4[5]),
    .Y(_153_)
  );
  NAND _339_ (
    .A(_072_),
    .B(dataIn0[5]),
    .Y(_154_)
  );
  NAND _340_ (
    .A(_153_),
    .B(_154_),
    .Y(_030_)
  );
  NAND _341_ (
    .A(selector_IDLE),
    .B(dataOut4[4]),
    .Y(_155_)
  );
  NAND _342_ (
    .A(_072_),
    .B(dataIn0[4]),
    .Y(_156_)
  );
  NAND _343_ (
    .A(_155_),
    .B(_156_),
    .Y(_029_)
  );
  NAND _344_ (
    .A(selector_IDLE),
    .B(dataOut4[3]),
    .Y(_157_)
  );
  NAND _345_ (
    .A(_072_),
    .B(dataIn0[3]),
    .Y(_158_)
  );
  NAND _346_ (
    .A(_157_),
    .B(_158_),
    .Y(_028_)
  );
  NAND _347_ (
    .A(selector_IDLE),
    .B(dataOut4[2]),
    .Y(_159_)
  );
  NAND _348_ (
    .A(_072_),
    .B(dataIn0[2]),
    .Y(_160_)
  );
  NAND _349_ (
    .A(_159_),
    .B(_160_),
    .Y(_027_)
  );
  NAND _350_ (
    .A(selector_IDLE),
    .B(dataOut4[1]),
    .Y(_161_)
  );
  NAND _351_ (
    .A(_072_),
    .B(dataIn0[1]),
    .Y(_162_)
  );
  NAND _352_ (
    .A(_161_),
    .B(_162_),
    .Y(_026_)
  );
  NAND _353_ (
    .A(selector_IDLE),
    .B(dataOut4[0]),
    .Y(_163_)
  );
  NAND _354_ (
    .A(_072_),
    .B(dataIn0[0]),
    .Y(_164_)
  );
  NAND _355_ (
    .A(_163_),
    .B(_164_),
    .Y(_025_)
  );
  NAND _356_ (
    .A(selector_IDLE),
    .B(dataIn3[7]),
    .Y(_165_)
  );
  NAND _357_ (
    .A(_072_),
    .B(dataOut3[7]),
    .Y(_166_)
  );
  NAND _358_ (
    .A(_165_),
    .B(_166_),
    .Y(_024_)
  );
  NAND _359_ (
    .A(selector_IDLE),
    .B(dataIn3[6]),
    .Y(_167_)
  );
  NAND _360_ (
    .A(_072_),
    .B(dataOut3[6]),
    .Y(_168_)
  );
  NAND _361_ (
    .A(_167_),
    .B(_168_),
    .Y(_023_)
  );
  NAND _362_ (
    .A(selector_IDLE),
    .B(dataIn3[5]),
    .Y(_169_)
  );
  NAND _363_ (
    .A(_072_),
    .B(dataOut3[5]),
    .Y(_170_)
  );
  NAND _364_ (
    .A(_169_),
    .B(_170_),
    .Y(_022_)
  );
  NAND _365_ (
    .A(selector_IDLE),
    .B(dataIn3[4]),
    .Y(_171_)
  );
  NAND _366_ (
    .A(_072_),
    .B(dataOut3[4]),
    .Y(_172_)
  );
  NAND _367_ (
    .A(_171_),
    .B(_172_),
    .Y(_021_)
  );
  NAND _368_ (
    .A(selector_IDLE),
    .B(dataIn3[3]),
    .Y(_173_)
  );
  NAND _369_ (
    .A(_072_),
    .B(dataOut3[3]),
    .Y(_174_)
  );
  NAND _370_ (
    .A(_173_),
    .B(_174_),
    .Y(_020_)
  );
  NAND _371_ (
    .A(selector_IDLE),
    .B(dataIn3[2]),
    .Y(_175_)
  );
  NAND _372_ (
    .A(_072_),
    .B(dataOut3[2]),
    .Y(_176_)
  );
  NAND _373_ (
    .A(_175_),
    .B(_176_),
    .Y(_019_)
  );
  NAND _374_ (
    .A(selector_IDLE),
    .B(dataIn3[1]),
    .Y(_177_)
  );
  NAND _375_ (
    .A(_072_),
    .B(dataOut3[1]),
    .Y(_178_)
  );
  NAND _376_ (
    .A(_177_),
    .B(_178_),
    .Y(_018_)
  );
  NAND _377_ (
    .A(selector_IDLE),
    .B(dataIn3[0]),
    .Y(_179_)
  );
  NAND _378_ (
    .A(_072_),
    .B(dataOut3[0]),
    .Y(_180_)
  );
  NAND _379_ (
    .A(_179_),
    .B(_180_),
    .Y(_017_)
  );
  NAND _380_ (
    .A(selector_IDLE),
    .B(dataIn2[7]),
    .Y(_181_)
  );
  NAND _381_ (
    .A(_072_),
    .B(dataOut2[7]),
    .Y(_182_)
  );
  NAND _382_ (
    .A(_181_),
    .B(_182_),
    .Y(_016_)
  );
  NAND _383_ (
    .A(selector_IDLE),
    .B(dataIn2[6]),
    .Y(_183_)
  );
  NAND _384_ (
    .A(_072_),
    .B(dataOut2[6]),
    .Y(_184_)
  );
  NAND _385_ (
    .A(_183_),
    .B(_184_),
    .Y(_015_)
  );
  NAND _386_ (
    .A(selector_IDLE),
    .B(dataIn2[5]),
    .Y(_185_)
  );
  NAND _387_ (
    .A(_072_),
    .B(dataOut2[5]),
    .Y(_186_)
  );
  NAND _388_ (
    .A(_185_),
    .B(_186_),
    .Y(_014_)
  );
  NAND _389_ (
    .A(selector_IDLE),
    .B(dataIn2[4]),
    .Y(_187_)
  );
  NAND _390_ (
    .A(_072_),
    .B(dataOut2[4]),
    .Y(_188_)
  );
  NAND _391_ (
    .A(_187_),
    .B(_188_),
    .Y(_013_)
  );
  NAND _392_ (
    .A(selector_IDLE),
    .B(dataIn2[3]),
    .Y(_189_)
  );
  NAND _393_ (
    .A(_072_),
    .B(dataOut2[3]),
    .Y(_190_)
  );
  NAND _394_ (
    .A(_189_),
    .B(_190_),
    .Y(_012_)
  );
  NAND _395_ (
    .A(selector_IDLE),
    .B(dataIn2[2]),
    .Y(_191_)
  );
  NAND _396_ (
    .A(_072_),
    .B(dataOut2[2]),
    .Y(_192_)
  );
  NAND _397_ (
    .A(_191_),
    .B(_192_),
    .Y(_011_)
  );
  NAND _398_ (
    .A(selector_IDLE),
    .B(dataIn2[1]),
    .Y(_193_)
  );
  NAND _399_ (
    .A(_072_),
    .B(dataOut2[1]),
    .Y(_194_)
  );
  NAND _400_ (
    .A(_193_),
    .B(_194_),
    .Y(_010_)
  );
  NAND _401_ (
    .A(selector_IDLE),
    .B(dataIn2[0]),
    .Y(_195_)
  );
  NAND _402_ (
    .A(_072_),
    .B(dataOut2[0]),
    .Y(_196_)
  );
  NAND _403_ (
    .A(_195_),
    .B(_196_),
    .Y(_009_)
  );
  NAND _404_ (
    .A(selector_IDLE),
    .B(dataIn1[7]),
    .Y(_197_)
  );
  NAND _405_ (
    .A(_072_),
    .B(dataOut1[7]),
    .Y(_198_)
  );
  NAND _406_ (
    .A(_197_),
    .B(_198_),
    .Y(_008_)
  );
  NAND _407_ (
    .A(selector_IDLE),
    .B(dataIn1[6]),
    .Y(_199_)
  );
  NAND _408_ (
    .A(_072_),
    .B(dataOut1[6]),
    .Y(_200_)
  );
  NAND _409_ (
    .A(_199_),
    .B(_200_),
    .Y(_007_)
  );
  NAND _410_ (
    .A(selector_IDLE),
    .B(dataIn1[5]),
    .Y(_201_)
  );
  NAND _411_ (
    .A(_072_),
    .B(dataOut1[5]),
    .Y(_202_)
  );
  NAND _412_ (
    .A(_201_),
    .B(_202_),
    .Y(_006_)
  );
  NAND _413_ (
    .A(selector_IDLE),
    .B(dataIn1[4]),
    .Y(_203_)
  );
  NAND _414_ (
    .A(_072_),
    .B(dataOut1[4]),
    .Y(_204_)
  );
  NAND _415_ (
    .A(_203_),
    .B(_204_),
    .Y(_005_)
  );
  NAND _416_ (
    .A(selector_IDLE),
    .B(dataIn1[3]),
    .Y(_205_)
  );
  NAND _417_ (
    .A(_072_),
    .B(dataOut1[3]),
    .Y(_206_)
  );
  NAND _418_ (
    .A(_205_),
    .B(_206_),
    .Y(_004_)
  );
  NAND _419_ (
    .A(selector_IDLE),
    .B(dataIn1[2]),
    .Y(_207_)
  );
  NAND _420_ (
    .A(_072_),
    .B(dataOut1[2]),
    .Y(_208_)
  );
  NAND _421_ (
    .A(_207_),
    .B(_208_),
    .Y(_003_)
  );
  NAND _422_ (
    .A(selector_IDLE),
    .B(dataIn1[1]),
    .Y(_209_)
  );
  NAND _423_ (
    .A(_072_),
    .B(dataOut1[1]),
    .Y(_210_)
  );
  NAND _424_ (
    .A(_209_),
    .B(_210_),
    .Y(_002_)
  );
  NAND _425_ (
    .A(selector_IDLE),
    .B(dataIn1[0]),
    .Y(_211_)
  );
  NAND _426_ (
    .A(_072_),
    .B(dataOut1[0]),
    .Y(_212_)
  );
  NAND _427_ (
    .A(_211_),
    .B(_212_),
    .Y(_001_)
  );
  NAND _428_ (
    .A(selector_IDLE),
    .B(validOut7),
    .Y(_213_)
  );
  NAND _429_ (
    .A(_072_),
    .B(validIn3),
    .Y(_214_)
  );
  NAND _430_ (
    .A(_213_),
    .B(_214_),
    .Y(_000_)
  );
  NAND _431_ (
    .A(selector_IDLE),
    .B(dataIn0[7]),
    .Y(_215_)
  );
  NAND _432_ (
    .A(_072_),
    .B(dataOut0[7]),
    .Y(_216_)
  );
  NAND _433_ (
    .A(_215_),
    .B(_216_),
    .Y(_071_)
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _434_ (
    .C(clk),
    .D(_000_),
    .Q(validOut7)
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _435_ (
    .C(clk),
    .D(_001_),
    .Q(dataOut1[0])
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _436_ (
    .C(clk),
    .D(_002_),
    .Q(dataOut1[1])
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _437_ (
    .C(clk),
    .D(_003_),
    .Q(dataOut1[2])
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _438_ (
    .C(clk),
    .D(_004_),
    .Q(dataOut1[3])
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _439_ (
    .C(clk),
    .D(_005_),
    .Q(dataOut1[4])
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _440_ (
    .C(clk),
    .D(_006_),
    .Q(dataOut1[5])
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _441_ (
    .C(clk),
    .D(_007_),
    .Q(dataOut1[6])
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _442_ (
    .C(clk),
    .D(_008_),
    .Q(dataOut1[7])
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _443_ (
    .C(clk),
    .D(_009_),
    .Q(dataOut2[0])
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _444_ (
    .C(clk),
    .D(_010_),
    .Q(dataOut2[1])
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _445_ (
    .C(clk),
    .D(_011_),
    .Q(dataOut2[2])
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _446_ (
    .C(clk),
    .D(_012_),
    .Q(dataOut2[3])
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _447_ (
    .C(clk),
    .D(_013_),
    .Q(dataOut2[4])
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _448_ (
    .C(clk),
    .D(_014_),
    .Q(dataOut2[5])
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _449_ (
    .C(clk),
    .D(_015_),
    .Q(dataOut2[6])
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _450_ (
    .C(clk),
    .D(_016_),
    .Q(dataOut2[7])
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _451_ (
    .C(clk),
    .D(_017_),
    .Q(dataOut3[0])
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _452_ (
    .C(clk),
    .D(_018_),
    .Q(dataOut3[1])
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _453_ (
    .C(clk),
    .D(_019_),
    .Q(dataOut3[2])
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _454_ (
    .C(clk),
    .D(_020_),
    .Q(dataOut3[3])
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _455_ (
    .C(clk),
    .D(_021_),
    .Q(dataOut3[4])
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _456_ (
    .C(clk),
    .D(_022_),
    .Q(dataOut3[5])
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _457_ (
    .C(clk),
    .D(_023_),
    .Q(dataOut3[6])
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _458_ (
    .C(clk),
    .D(_024_),
    .Q(dataOut3[7])
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _459_ (
    .C(clk),
    .D(_025_),
    .Q(dataOut4[0])
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _460_ (
    .C(clk),
    .D(_026_),
    .Q(dataOut4[1])
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _461_ (
    .C(clk),
    .D(_027_),
    .Q(dataOut4[2])
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _462_ (
    .C(clk),
    .D(_028_),
    .Q(dataOut4[3])
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _463_ (
    .C(clk),
    .D(_029_),
    .Q(dataOut4[4])
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _464_ (
    .C(clk),
    .D(_030_),
    .Q(dataOut4[5])
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _465_ (
    .C(clk),
    .D(_031_),
    .Q(dataOut4[6])
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _466_ (
    .C(clk),
    .D(_032_),
    .Q(dataOut4[7])
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _467_ (
    .C(clk),
    .D(_033_),
    .Q(dataOut5[0])
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _468_ (
    .C(clk),
    .D(_034_),
    .Q(dataOut5[1])
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _469_ (
    .C(clk),
    .D(_035_),
    .Q(dataOut5[2])
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _470_ (
    .C(clk),
    .D(_036_),
    .Q(dataOut5[3])
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _471_ (
    .C(clk),
    .D(_037_),
    .Q(dataOut5[4])
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _472_ (
    .C(clk),
    .D(_038_),
    .Q(dataOut5[5])
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _473_ (
    .C(clk),
    .D(_039_),
    .Q(dataOut5[6])
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _474_ (
    .C(clk),
    .D(_040_),
    .Q(dataOut5[7])
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _475_ (
    .C(clk),
    .D(_041_),
    .Q(dataOut6[0])
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _476_ (
    .C(clk),
    .D(_042_),
    .Q(dataOut6[1])
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _477_ (
    .C(clk),
    .D(_043_),
    .Q(dataOut6[2])
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _478_ (
    .C(clk),
    .D(_044_),
    .Q(dataOut6[3])
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _479_ (
    .C(clk),
    .D(_045_),
    .Q(dataOut6[4])
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _480_ (
    .C(clk),
    .D(_046_),
    .Q(dataOut6[5])
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _481_ (
    .C(clk),
    .D(_047_),
    .Q(dataOut6[6])
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _482_ (
    .C(clk),
    .D(_048_),
    .Q(dataOut6[7])
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _483_ (
    .C(clk),
    .D(_049_),
    .Q(dataOut7[0])
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _484_ (
    .C(clk),
    .D(_050_),
    .Q(dataOut7[1])
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _485_ (
    .C(clk),
    .D(_051_),
    .Q(dataOut7[2])
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _486_ (
    .C(clk),
    .D(_052_),
    .Q(dataOut7[3])
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _487_ (
    .C(clk),
    .D(_053_),
    .Q(dataOut7[4])
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _488_ (
    .C(clk),
    .D(_054_),
    .Q(dataOut7[5])
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _489_ (
    .C(clk),
    .D(_055_),
    .Q(dataOut7[6])
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _490_ (
    .C(clk),
    .D(_056_),
    .Q(dataOut7[7])
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _491_ (
    .C(clk),
    .D(_057_),
    .Q(validOut0)
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _492_ (
    .C(clk),
    .D(_058_),
    .Q(validOut1)
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _493_ (
    .C(clk),
    .D(_059_),
    .Q(validOut2)
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _494_ (
    .C(clk),
    .D(_060_),
    .Q(validOut3)
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _495_ (
    .C(clk),
    .D(_061_),
    .Q(validOut4)
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _496_ (
    .C(clk),
    .D(_062_),
    .Q(validOut5)
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _497_ (
    .C(clk),
    .D(_063_),
    .Q(validOut6)
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _498_ (
    .C(clk),
    .D(_064_),
    .Q(dataOut0[0])
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _499_ (
    .C(clk),
    .D(_065_),
    .Q(dataOut0[1])
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _500_ (
    .C(clk),
    .D(_066_),
    .Q(dataOut0[2])
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _501_ (
    .C(clk),
    .D(_067_),
    .Q(dataOut0[3])
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _502_ (
    .C(clk),
    .D(_068_),
    .Q(dataOut0[4])
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _503_ (
    .C(clk),
    .D(_069_),
    .Q(dataOut0[5])
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _504_ (
    .C(clk),
    .D(_070_),
    .Q(dataOut0[6])
  );
  (* src = "Recirculador_sintetizado.v:30.2-77.6" *)
  DFF _505_ (
    .C(clk),
    .D(_071_),
    .Q(dataOut0[7])
  );
endmodule
