/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "ParaleloSerial_PhyTX.v:1" *)
module ParaleloSerial_PhyTX_Synth(clk, validIn, reset, inputP, outputS);
  (* src = "ParaleloSerial_PhyTX.v:16" *)
  wire [2:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  (* src = "ParaleloSerial_PhyTX.v:2" *)
  input clk;
  (* src = "ParaleloSerial_PhyTX.v:5" *)
  input [7:0] inputP;
  (* init = 1'h0 *)
  (* src = "ParaleloSerial_PhyTX.v:6" *)
  output outputS;
  (* src = "ParaleloSerial_PhyTX.v:4" *)
  input reset;
  (* init = 3'h0 *)
  (* src = "ParaleloSerial_PhyTX.v:9" *)
  wire [2:0] selector;
  (* src = "ParaleloSerial_PhyTX.v:3" *)
  input validIn;
  NOT _40_ (
    .A(selector[2]),
    .Y(_01_)
  );
  NOT _41_ (
    .A(selector[0]),
    .Y(_02_)
  );
  NOT _42_ (
    .A(reset),
    .Y(_03_)
  );
  NOT _43_ (
    .A(validIn),
    .Y(_04_)
  );
  NOT _44_ (
    .A(inputP[5]),
    .Y(_05_)
  );
  NOT _45_ (
    .A(inputP[1]),
    .Y(_06_)
  );
  NAND _46_ (
    .A(selector[0]),
    .B(selector[1]),
    .Y(_07_)
  );
  NOT _47_ (
    .A(_07_),
    .Y(_08_)
  );
  NAND _48_ (
    .A(inputP[4]),
    .B(_08_),
    .Y(_09_)
  );
  NOR _49_ (
    .A(_02_),
    .B(selector[1]),
    .Y(_10_)
  );
  NAND _50_ (
    .A(inputP[6]),
    .B(_10_),
    .Y(_11_)
  );
  NOR _51_ (
    .A(selector[0]),
    .B(selector[1]),
    .Y(_12_)
  );
  NAND _52_ (
    .A(inputP[7]),
    .B(_12_),
    .Y(_13_)
  );
  NAND _53_ (
    .A(_02_),
    .B(selector[1]),
    .Y(_14_)
  );
  NOR _54_ (
    .A(_05_),
    .B(_14_),
    .Y(_15_)
  );
  NAND _55_ (
    .A(_09_),
    .B(_11_),
    .Y(_16_)
  );
  NOR _56_ (
    .A(selector[2]),
    .B(_15_),
    .Y(_17_)
  );
  NAND _57_ (
    .A(_13_),
    .B(_17_),
    .Y(_18_)
  );
  NOR _58_ (
    .A(_16_),
    .B(_18_),
    .Y(_19_)
  );
  NAND _59_ (
    .A(inputP[2]),
    .B(_10_),
    .Y(_20_)
  );
  NOR _60_ (
    .A(_06_),
    .B(_14_),
    .Y(_21_)
  );
  NAND _61_ (
    .A(inputP[3]),
    .B(_12_),
    .Y(_22_)
  );
  NAND _62_ (
    .A(inputP[0]),
    .B(_08_),
    .Y(_23_)
  );
  NAND _63_ (
    .A(_20_),
    .B(_22_),
    .Y(_24_)
  );
  NOR _64_ (
    .A(_01_),
    .B(_21_),
    .Y(_25_)
  );
  NAND _65_ (
    .A(_23_),
    .B(_25_),
    .Y(_26_)
  );
  NOR _66_ (
    .A(_24_),
    .B(_26_),
    .Y(_27_)
  );
  NOR _67_ (
    .A(_19_),
    .B(_27_),
    .Y(_28_)
  );
  NOR _68_ (
    .A(_04_),
    .B(_28_),
    .Y(_29_)
  );
  NOR _69_ (
    .A(selector[2]),
    .B(_10_),
    .Y(_30_)
  );
  NOT _70_ (
    .A(_30_),
    .Y(_31_)
  );
  NOR _71_ (
    .A(_01_),
    .B(selector[1]),
    .Y(_32_)
  );
  NOR _72_ (
    .A(validIn),
    .B(_32_),
    .Y(_33_)
  );
  NAND _73_ (
    .A(_31_),
    .B(_33_),
    .Y(_34_)
  );
  NAND _74_ (
    .A(reset),
    .B(_34_),
    .Y(_35_)
  );
  NOR _75_ (
    .A(_29_),
    .B(_35_),
    .Y(outputS)
  );
  NOR _76_ (
    .A(selector[0]),
    .B(_03_),
    .Y(_00_[0])
  );
  NAND _77_ (
    .A(reset),
    .B(_07_),
    .Y(_36_)
  );
  NOR _78_ (
    .A(_12_),
    .B(_36_),
    .Y(_00_[1])
  );
  NOR _79_ (
    .A(_01_),
    .B(_08_),
    .Y(_37_)
  );
  NOR _80_ (
    .A(selector[2]),
    .B(_07_),
    .Y(_38_)
  );
  NOR _81_ (
    .A(_37_),
    .B(_38_),
    .Y(_39_)
  );
  NOR _82_ (
    .A(_03_),
    .B(_39_),
    .Y(_00_[2])
  );
  (* src = "ParaleloSerial_PhyTX.v:16" *)
  DFF _83_ (
    .C(clk),
    .D(_00_[0]),
    .Q(selector[0])
  );
  (* src = "ParaleloSerial_PhyTX.v:16" *)
  DFF _84_ (
    .C(clk),
    .D(_00_[1]),
    .Q(selector[1])
  );
  (* src = "ParaleloSerial_PhyTX.v:16" *)
  DFF _85_ (
    .C(clk),
    .D(_00_[2]),
    .Q(selector[2])
  );
endmodule
