/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "ParaleloSerial_PhyRX.v:1" *)
module ParaleloSerial_PhyRX_Synth(clk, active, reset, outputS);
  (* src = "ParaleloSerial_PhyRX.v:10" *)
  wire [2:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  (* src = "ParaleloSerial_PhyRX.v:3" *)
  input active;
  (* src = "ParaleloSerial_PhyRX.v:2" *)
  input clk;
  (* src = "ParaleloSerial_PhyRX.v:5" *)
  output outputS;
  (* src = "ParaleloSerial_PhyRX.v:4" *)
  input reset;
  (* src = "ParaleloSerial_PhyRX.v:8" *)
  wire [2:0] selector;
  NOT _20_ (
    .A(selector[1]),
    .Y(_01_)
  );
  NOT _21_ (
    .A(selector[0]),
    .Y(_02_)
  );
  NOT _22_ (
    .A(active),
    .Y(_03_)
  );
  NOT _23_ (
    .A(reset),
    .Y(_04_)
  );
  NAND _24_ (
    .A(selector[1]),
    .B(selector[2]),
    .Y(_05_)
  );
  NAND _25_ (
    .A(reset),
    .B(_05_),
    .Y(_06_)
  );
  NOT _26_ (
    .A(_06_),
    .Y(_07_)
  );
  NOR _27_ (
    .A(_02_),
    .B(active),
    .Y(_08_)
  );
  NOR _28_ (
    .A(selector[0]),
    .B(_03_),
    .Y(_09_)
  );
  NOR _29_ (
    .A(_08_),
    .B(_09_),
    .Y(_10_)
  );
  NOR _30_ (
    .A(selector[1]),
    .B(selector[2]),
    .Y(_11_)
  );
  NOT _31_ (
    .A(_11_),
    .Y(_12_)
  );
  NOR _32_ (
    .A(_10_),
    .B(_12_),
    .Y(_13_)
  );
  NOR _33_ (
    .A(_06_),
    .B(_13_),
    .Y(outputS)
  );
  NOR _34_ (
    .A(selector[0]),
    .B(_04_),
    .Y(_00_[0])
  );
  NOR _35_ (
    .A(_01_),
    .B(_02_),
    .Y(_14_)
  );
  NOR _36_ (
    .A(selector[1]),
    .B(selector[0]),
    .Y(_15_)
  );
  NOT _37_ (
    .A(_15_),
    .Y(_16_)
  );
  NAND _38_ (
    .A(reset),
    .B(_16_),
    .Y(_17_)
  );
  NOR _39_ (
    .A(_14_),
    .B(_17_),
    .Y(_00_[1])
  );
  NOR _40_ (
    .A(selector[2]),
    .B(_14_),
    .Y(_18_)
  );
  NOR _41_ (
    .A(_07_),
    .B(_00_[0]),
    .Y(_19_)
  );
  NOR _42_ (
    .A(_18_),
    .B(_19_),
    .Y(_00_[2])
  );
  (* src = "ParaleloSerial_PhyRX.v:10" *)
  DFF _43_ (
    .C(clk),
    .D(_00_[0]),
    .Q(selector[0])
  );
  (* src = "ParaleloSerial_PhyRX.v:10" *)
  DFF _44_ (
    .C(clk),
    .D(_00_[1]),
    .Q(selector[1])
  );
  (* src = "ParaleloSerial_PhyRX.v:10" *)
  DFF _45_ (
    .C(clk),
    .D(_00_[2]),
    .Q(selector[2])
  );
endmodule
