/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* cells_not_processed =  1  *)
(* src = "Recirculador_sintetizado.v:2" *)
module Recirculador_sintetizado(clk, dataIn0, dataIn1, dataIn2, dataIn3, validIn0, validIn1, validIn2, validIn3, selector_IDLE, reset, dataOut0_synth, dataOut1_synth, dataOut2_synth, dataOut3_synth, dataOut4_synth, dataOut5_synth, dataOut6_synth, dataOut7_synth, validOut0_synth, validOut1_synth, validOut2_synth, validOut3_synth, validOut4_synth, validOut5_synth, validOut6_synth, validOut7_synth);
  (* src = "Recirculador_sintetizado.v:32" *)
  wire [7:0] _000_;
  (* src = "Recirculador_sintetizado.v:32" *)
  wire [7:0] _001_;
  (* src = "Recirculador_sintetizado.v:32" *)
  wire [7:0] _002_;
  (* src = "Recirculador_sintetizado.v:32" *)
  wire [7:0] _003_;
  (* src = "Recirculador_sintetizado.v:32" *)
  wire [7:0] _004_;
  (* src = "Recirculador_sintetizado.v:32" *)
  wire [7:0] _005_;
  (* src = "Recirculador_sintetizado.v:32" *)
  wire [7:0] _006_;
  (* src = "Recirculador_sintetizado.v:32" *)
  wire [7:0] _007_;
  (* src = "Recirculador_sintetizado.v:32" *)
  wire _008_;
  (* src = "Recirculador_sintetizado.v:32" *)
  wire _009_;
  (* src = "Recirculador_sintetizado.v:32" *)
  wire _010_;
  (* src = "Recirculador_sintetizado.v:32" *)
  wire _011_;
  (* src = "Recirculador_sintetizado.v:32" *)
  wire _012_;
  (* src = "Recirculador_sintetizado.v:32" *)
  wire _013_;
  (* src = "Recirculador_sintetizado.v:32" *)
  wire _014_;
  (* src = "Recirculador_sintetizado.v:32" *)
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  (* src = "Recirculador_sintetizado.v:3" *)
  input clk;
  (* src = "Recirculador_sintetizado.v:4" *)
  input [7:0] dataIn0;
  (* src = "Recirculador_sintetizado.v:5" *)
  input [7:0] dataIn1;
  (* src = "Recirculador_sintetizado.v:6" *)
  input [7:0] dataIn2;
  (* src = "Recirculador_sintetizado.v:7" *)
  input [7:0] dataIn3;
  (* src = "Recirculador_sintetizado.v:14" *)
  output [7:0] dataOut0_synth;
  (* src = "Recirculador_sintetizado.v:15" *)
  output [7:0] dataOut1_synth;
  (* src = "Recirculador_sintetizado.v:16" *)
  output [7:0] dataOut2_synth;
  (* src = "Recirculador_sintetizado.v:17" *)
  output [7:0] dataOut3_synth;
  (* src = "Recirculador_sintetizado.v:18" *)
  output [7:0] dataOut4_synth;
  (* src = "Recirculador_sintetizado.v:19" *)
  output [7:0] dataOut5_synth;
  (* src = "Recirculador_sintetizado.v:20" *)
  output [7:0] dataOut6_synth;
  (* src = "Recirculador_sintetizado.v:21" *)
  output [7:0] dataOut7_synth;
  (* src = "Recirculador_sintetizado.v:13" *)
  input reset;
  (* src = "Recirculador_sintetizado.v:12" *)
  input selector_IDLE;
  (* src = "Recirculador_sintetizado.v:8" *)
  input validIn0;
  (* src = "Recirculador_sintetizado.v:9" *)
  input validIn1;
  (* src = "Recirculador_sintetizado.v:10" *)
  input validIn2;
  (* src = "Recirculador_sintetizado.v:11" *)
  input validIn3;
  (* src = "Recirculador_sintetizado.v:22" *)
  output validOut0_synth;
  (* src = "Recirculador_sintetizado.v:23" *)
  output validOut1_synth;
  (* src = "Recirculador_sintetizado.v:24" *)
  output validOut2_synth;
  (* src = "Recirculador_sintetizado.v:25" *)
  output validOut3_synth;
  (* src = "Recirculador_sintetizado.v:26" *)
  output validOut4_synth;
  (* src = "Recirculador_sintetizado.v:27" *)
  output validOut5_synth;
  (* src = "Recirculador_sintetizado.v:28" *)
  output validOut6_synth;
  (* src = "Recirculador_sintetizado.v:29" *)
  output validOut7_synth;
  NOT _292_ (
    .A(validIn2),
    .Y(_016_)
  );
  NOT _293_ (
    .A(validIn1),
    .Y(_017_)
  );
  NOT _294_ (
    .A(validIn0),
    .Y(_018_)
  );
  NOT _295_ (
    .A(dataIn3[0]),
    .Y(_019_)
  );
  NOT _296_ (
    .A(dataIn3[1]),
    .Y(_020_)
  );
  NOT _297_ (
    .A(dataIn3[2]),
    .Y(_021_)
  );
  NOT _298_ (
    .A(dataIn3[3]),
    .Y(_022_)
  );
  NOT _299_ (
    .A(dataIn3[4]),
    .Y(_023_)
  );
  NOT _300_ (
    .A(dataIn3[5]),
    .Y(_024_)
  );
  NOT _301_ (
    .A(dataIn3[6]),
    .Y(_025_)
  );
  NOT _302_ (
    .A(dataIn3[7]),
    .Y(_026_)
  );
  NOT _303_ (
    .A(dataIn2[0]),
    .Y(_027_)
  );
  NOT _304_ (
    .A(dataIn2[1]),
    .Y(_028_)
  );
  NOT _305_ (
    .A(dataIn2[2]),
    .Y(_029_)
  );
  NOT _306_ (
    .A(dataIn2[3]),
    .Y(_030_)
  );
  NOT _307_ (
    .A(dataIn2[4]),
    .Y(_031_)
  );
  NOT _308_ (
    .A(dataIn2[5]),
    .Y(_032_)
  );
  NOT _309_ (
    .A(dataIn2[6]),
    .Y(_033_)
  );
  NOT _310_ (
    .A(dataIn2[7]),
    .Y(_034_)
  );
  NOT _311_ (
    .A(dataIn1[0]),
    .Y(_035_)
  );
  NOT _312_ (
    .A(dataIn1[1]),
    .Y(_036_)
  );
  NOT _313_ (
    .A(dataIn1[2]),
    .Y(_037_)
  );
  NOT _314_ (
    .A(dataIn1[3]),
    .Y(_038_)
  );
  NOT _315_ (
    .A(dataIn1[4]),
    .Y(_039_)
  );
  NOT _316_ (
    .A(dataIn1[5]),
    .Y(_040_)
  );
  NOT _317_ (
    .A(dataIn1[6]),
    .Y(_041_)
  );
  NOT _318_ (
    .A(dataIn1[7]),
    .Y(_042_)
  );
  NOT _319_ (
    .A(dataIn0[0]),
    .Y(_043_)
  );
  NOT _320_ (
    .A(dataIn0[1]),
    .Y(_044_)
  );
  NOT _321_ (
    .A(dataIn0[2]),
    .Y(_045_)
  );
  NOT _322_ (
    .A(dataIn0[3]),
    .Y(_046_)
  );
  NOT _323_ (
    .A(dataIn0[4]),
    .Y(_047_)
  );
  NOT _324_ (
    .A(dataIn0[5]),
    .Y(_048_)
  );
  NOT _325_ (
    .A(dataIn0[6]),
    .Y(_049_)
  );
  NOT _326_ (
    .A(dataIn0[7]),
    .Y(_050_)
  );
  NOT _327_ (
    .A(dataOut7_synth[0]),
    .Y(_051_)
  );
  NOT _328_ (
    .A(dataOut7_synth[1]),
    .Y(_052_)
  );
  NOT _329_ (
    .A(dataOut7_synth[2]),
    .Y(_053_)
  );
  NOT _330_ (
    .A(dataOut7_synth[3]),
    .Y(_054_)
  );
  NOT _331_ (
    .A(dataOut7_synth[4]),
    .Y(_055_)
  );
  NOT _332_ (
    .A(dataOut7_synth[5]),
    .Y(_056_)
  );
  NOT _333_ (
    .A(dataOut7_synth[6]),
    .Y(_057_)
  );
  NOT _334_ (
    .A(dataOut7_synth[7]),
    .Y(_058_)
  );
  NOT _335_ (
    .A(dataOut6_synth[0]),
    .Y(_059_)
  );
  NOT _336_ (
    .A(dataOut6_synth[1]),
    .Y(_060_)
  );
  NOT _337_ (
    .A(dataOut6_synth[2]),
    .Y(_061_)
  );
  NOT _338_ (
    .A(dataOut6_synth[3]),
    .Y(_062_)
  );
  NOT _339_ (
    .A(dataOut6_synth[4]),
    .Y(_063_)
  );
  NOT _340_ (
    .A(dataOut6_synth[5]),
    .Y(_064_)
  );
  NOT _341_ (
    .A(dataOut6_synth[6]),
    .Y(_065_)
  );
  NOT _342_ (
    .A(dataOut6_synth[7]),
    .Y(_066_)
  );
  NOT _343_ (
    .A(dataOut5_synth[0]),
    .Y(_067_)
  );
  NOT _344_ (
    .A(dataOut5_synth[1]),
    .Y(_068_)
  );
  NOT _345_ (
    .A(dataOut5_synth[2]),
    .Y(_069_)
  );
  NOT _346_ (
    .A(dataOut5_synth[3]),
    .Y(_070_)
  );
  NOT _347_ (
    .A(dataOut5_synth[4]),
    .Y(_071_)
  );
  NOT _348_ (
    .A(dataOut5_synth[5]),
    .Y(_072_)
  );
  NOT _349_ (
    .A(dataOut5_synth[6]),
    .Y(_073_)
  );
  NOT _350_ (
    .A(dataOut5_synth[7]),
    .Y(_074_)
  );
  NOT _351_ (
    .A(dataOut4_synth[0]),
    .Y(_075_)
  );
  NOT _352_ (
    .A(dataOut4_synth[1]),
    .Y(_076_)
  );
  NOT _353_ (
    .A(dataOut4_synth[2]),
    .Y(_077_)
  );
  NOT _354_ (
    .A(dataOut4_synth[3]),
    .Y(_078_)
  );
  NOT _355_ (
    .A(dataOut4_synth[4]),
    .Y(_079_)
  );
  NOT _356_ (
    .A(dataOut4_synth[5]),
    .Y(_080_)
  );
  NOT _357_ (
    .A(dataOut4_synth[6]),
    .Y(_081_)
  );
  NOT _358_ (
    .A(dataOut4_synth[7]),
    .Y(_082_)
  );
  NOT _359_ (
    .A(validIn3),
    .Y(_083_)
  );
  NAND _360_ (
    .A(validIn1),
    .B(reset),
    .Y(_084_)
  );
  NOR _361_ (
    .A(selector_IDLE),
    .B(_084_),
    .Y(_013_)
  );
  NAND _362_ (
    .A(validIn3),
    .B(reset),
    .Y(_085_)
  );
  NOR _363_ (
    .A(selector_IDLE),
    .B(_085_),
    .Y(_015_)
  );
  NAND _364_ (
    .A(validIn2),
    .B(reset),
    .Y(_086_)
  );
  NOR _365_ (
    .A(selector_IDLE),
    .B(_086_),
    .Y(_014_)
  );
  NOR _366_ (
    .A(validOut2_synth),
    .B(selector_IDLE),
    .Y(_087_)
  );
  NAND _367_ (
    .A(_016_),
    .B(selector_IDLE),
    .Y(_088_)
  );
  NAND _368_ (
    .A(reset),
    .B(_088_),
    .Y(_089_)
  );
  NOR _369_ (
    .A(_087_),
    .B(_089_),
    .Y(_010_)
  );
  NAND _370_ (
    .A(validIn0),
    .B(reset),
    .Y(_090_)
  );
  NOR _371_ (
    .A(selector_IDLE),
    .B(_090_),
    .Y(_012_)
  );
  NOR _372_ (
    .A(selector_IDLE),
    .B(validOut3_synth),
    .Y(_091_)
  );
  NAND _373_ (
    .A(selector_IDLE),
    .B(_083_),
    .Y(_092_)
  );
  NAND _374_ (
    .A(reset),
    .B(_092_),
    .Y(_093_)
  );
  NOR _375_ (
    .A(_091_),
    .B(_093_),
    .Y(_011_)
  );
  NOR _376_ (
    .A(selector_IDLE),
    .B(dataIn3[0]),
    .Y(_094_)
  );
  NAND _377_ (
    .A(selector_IDLE),
    .B(_051_),
    .Y(_095_)
  );
  NAND _378_ (
    .A(reset),
    .B(_095_),
    .Y(_096_)
  );
  NOR _379_ (
    .A(_094_),
    .B(_096_),
    .Y(_007_[0])
  );
  NOR _380_ (
    .A(selector_IDLE),
    .B(dataIn3[1]),
    .Y(_097_)
  );
  NAND _381_ (
    .A(selector_IDLE),
    .B(_052_),
    .Y(_098_)
  );
  NAND _382_ (
    .A(reset),
    .B(_098_),
    .Y(_099_)
  );
  NOR _383_ (
    .A(_097_),
    .B(_099_),
    .Y(_007_[1])
  );
  NOR _384_ (
    .A(selector_IDLE),
    .B(dataIn3[2]),
    .Y(_100_)
  );
  NAND _385_ (
    .A(selector_IDLE),
    .B(_053_),
    .Y(_101_)
  );
  NAND _386_ (
    .A(reset),
    .B(_101_),
    .Y(_102_)
  );
  NOR _387_ (
    .A(_100_),
    .B(_102_),
    .Y(_007_[2])
  );
  NOR _388_ (
    .A(selector_IDLE),
    .B(dataIn3[3]),
    .Y(_103_)
  );
  NAND _389_ (
    .A(selector_IDLE),
    .B(_054_),
    .Y(_104_)
  );
  NAND _390_ (
    .A(reset),
    .B(_104_),
    .Y(_105_)
  );
  NOR _391_ (
    .A(_103_),
    .B(_105_),
    .Y(_007_[3])
  );
  NOR _392_ (
    .A(selector_IDLE),
    .B(dataIn3[4]),
    .Y(_106_)
  );
  NAND _393_ (
    .A(selector_IDLE),
    .B(_055_),
    .Y(_107_)
  );
  NAND _394_ (
    .A(reset),
    .B(_107_),
    .Y(_108_)
  );
  NOR _395_ (
    .A(_106_),
    .B(_108_),
    .Y(_007_[4])
  );
  NOR _396_ (
    .A(selector_IDLE),
    .B(dataIn3[5]),
    .Y(_109_)
  );
  NAND _397_ (
    .A(selector_IDLE),
    .B(_056_),
    .Y(_110_)
  );
  NAND _398_ (
    .A(reset),
    .B(_110_),
    .Y(_111_)
  );
  NOR _399_ (
    .A(_109_),
    .B(_111_),
    .Y(_007_[5])
  );
  NOR _400_ (
    .A(selector_IDLE),
    .B(dataIn3[6]),
    .Y(_112_)
  );
  NAND _401_ (
    .A(selector_IDLE),
    .B(_057_),
    .Y(_113_)
  );
  NAND _402_ (
    .A(reset),
    .B(_113_),
    .Y(_114_)
  );
  NOR _403_ (
    .A(_112_),
    .B(_114_),
    .Y(_007_[6])
  );
  NOR _404_ (
    .A(selector_IDLE),
    .B(dataIn3[7]),
    .Y(_115_)
  );
  NAND _405_ (
    .A(selector_IDLE),
    .B(_058_),
    .Y(_116_)
  );
  NAND _406_ (
    .A(reset),
    .B(_116_),
    .Y(_117_)
  );
  NOR _407_ (
    .A(_115_),
    .B(_117_),
    .Y(_007_[7])
  );
  NOR _408_ (
    .A(selector_IDLE),
    .B(validOut1_synth),
    .Y(_118_)
  );
  NAND _409_ (
    .A(selector_IDLE),
    .B(_017_),
    .Y(_119_)
  );
  NAND _410_ (
    .A(reset),
    .B(_119_),
    .Y(_120_)
  );
  NOR _411_ (
    .A(_118_),
    .B(_120_),
    .Y(_009_)
  );
  NOR _412_ (
    .A(selector_IDLE),
    .B(validOut0_synth),
    .Y(_121_)
  );
  NAND _413_ (
    .A(selector_IDLE),
    .B(_018_),
    .Y(_122_)
  );
  NAND _414_ (
    .A(reset),
    .B(_122_),
    .Y(_123_)
  );
  NOR _415_ (
    .A(_121_),
    .B(_123_),
    .Y(_008_)
  );
  NOR _416_ (
    .A(selector_IDLE),
    .B(dataIn0[0]),
    .Y(_124_)
  );
  NAND _417_ (
    .A(selector_IDLE),
    .B(_075_),
    .Y(_125_)
  );
  NAND _418_ (
    .A(reset),
    .B(_125_),
    .Y(_126_)
  );
  NOR _419_ (
    .A(_124_),
    .B(_126_),
    .Y(_004_[0])
  );
  NOR _420_ (
    .A(selector_IDLE),
    .B(dataIn0[1]),
    .Y(_127_)
  );
  NAND _421_ (
    .A(selector_IDLE),
    .B(_076_),
    .Y(_128_)
  );
  NAND _422_ (
    .A(reset),
    .B(_128_),
    .Y(_129_)
  );
  NOR _423_ (
    .A(_127_),
    .B(_129_),
    .Y(_004_[1])
  );
  NOR _424_ (
    .A(selector_IDLE),
    .B(dataIn0[2]),
    .Y(_130_)
  );
  NAND _425_ (
    .A(selector_IDLE),
    .B(_077_),
    .Y(_131_)
  );
  NAND _426_ (
    .A(reset),
    .B(_131_),
    .Y(_132_)
  );
  NOR _427_ (
    .A(_130_),
    .B(_132_),
    .Y(_004_[2])
  );
  NOR _428_ (
    .A(selector_IDLE),
    .B(dataIn0[3]),
    .Y(_133_)
  );
  NAND _429_ (
    .A(selector_IDLE),
    .B(_078_),
    .Y(_134_)
  );
  NAND _430_ (
    .A(reset),
    .B(_134_),
    .Y(_135_)
  );
  NOR _431_ (
    .A(_133_),
    .B(_135_),
    .Y(_004_[3])
  );
  NOR _432_ (
    .A(selector_IDLE),
    .B(dataIn0[4]),
    .Y(_136_)
  );
  NAND _433_ (
    .A(selector_IDLE),
    .B(_079_),
    .Y(_137_)
  );
  NAND _434_ (
    .A(reset),
    .B(_137_),
    .Y(_138_)
  );
  NOR _435_ (
    .A(_136_),
    .B(_138_),
    .Y(_004_[4])
  );
  NOR _436_ (
    .A(selector_IDLE),
    .B(dataIn0[5]),
    .Y(_139_)
  );
  NAND _437_ (
    .A(selector_IDLE),
    .B(_080_),
    .Y(_140_)
  );
  NAND _438_ (
    .A(reset),
    .B(_140_),
    .Y(_141_)
  );
  NOR _439_ (
    .A(_139_),
    .B(_141_),
    .Y(_004_[5])
  );
  NOR _440_ (
    .A(selector_IDLE),
    .B(dataIn0[6]),
    .Y(_142_)
  );
  NAND _441_ (
    .A(selector_IDLE),
    .B(_081_),
    .Y(_143_)
  );
  NAND _442_ (
    .A(reset),
    .B(_143_),
    .Y(_144_)
  );
  NOR _443_ (
    .A(_142_),
    .B(_144_),
    .Y(_004_[6])
  );
  NOR _444_ (
    .A(selector_IDLE),
    .B(dataIn0[7]),
    .Y(_145_)
  );
  NAND _445_ (
    .A(selector_IDLE),
    .B(_082_),
    .Y(_146_)
  );
  NAND _446_ (
    .A(reset),
    .B(_146_),
    .Y(_147_)
  );
  NOR _447_ (
    .A(_145_),
    .B(_147_),
    .Y(_004_[7])
  );
  NOR _448_ (
    .A(selector_IDLE),
    .B(dataIn2[0]),
    .Y(_148_)
  );
  NAND _449_ (
    .A(selector_IDLE),
    .B(_059_),
    .Y(_149_)
  );
  NAND _450_ (
    .A(reset),
    .B(_149_),
    .Y(_150_)
  );
  NOR _451_ (
    .A(_148_),
    .B(_150_),
    .Y(_006_[0])
  );
  NOR _452_ (
    .A(selector_IDLE),
    .B(dataIn2[1]),
    .Y(_151_)
  );
  NAND _453_ (
    .A(selector_IDLE),
    .B(_060_),
    .Y(_152_)
  );
  NAND _454_ (
    .A(reset),
    .B(_152_),
    .Y(_153_)
  );
  NOR _455_ (
    .A(_151_),
    .B(_153_),
    .Y(_006_[1])
  );
  NOR _456_ (
    .A(selector_IDLE),
    .B(dataIn2[2]),
    .Y(_154_)
  );
  NAND _457_ (
    .A(selector_IDLE),
    .B(_061_),
    .Y(_155_)
  );
  NAND _458_ (
    .A(reset),
    .B(_155_),
    .Y(_156_)
  );
  NOR _459_ (
    .A(_154_),
    .B(_156_),
    .Y(_006_[2])
  );
  NOR _460_ (
    .A(selector_IDLE),
    .B(dataIn2[3]),
    .Y(_157_)
  );
  NAND _461_ (
    .A(selector_IDLE),
    .B(_062_),
    .Y(_158_)
  );
  NAND _462_ (
    .A(reset),
    .B(_158_),
    .Y(_159_)
  );
  NOR _463_ (
    .A(_157_),
    .B(_159_),
    .Y(_006_[3])
  );
  NOR _464_ (
    .A(selector_IDLE),
    .B(dataIn2[4]),
    .Y(_160_)
  );
  NAND _465_ (
    .A(selector_IDLE),
    .B(_063_),
    .Y(_161_)
  );
  NAND _466_ (
    .A(reset),
    .B(_161_),
    .Y(_162_)
  );
  NOR _467_ (
    .A(_160_),
    .B(_162_),
    .Y(_006_[4])
  );
  NOR _468_ (
    .A(selector_IDLE),
    .B(dataIn2[5]),
    .Y(_163_)
  );
  NAND _469_ (
    .A(selector_IDLE),
    .B(_064_),
    .Y(_164_)
  );
  NAND _470_ (
    .A(reset),
    .B(_164_),
    .Y(_165_)
  );
  NOR _471_ (
    .A(_163_),
    .B(_165_),
    .Y(_006_[5])
  );
  NOR _472_ (
    .A(selector_IDLE),
    .B(dataIn2[6]),
    .Y(_166_)
  );
  NAND _473_ (
    .A(selector_IDLE),
    .B(_065_),
    .Y(_167_)
  );
  NAND _474_ (
    .A(reset),
    .B(_167_),
    .Y(_168_)
  );
  NOR _475_ (
    .A(_166_),
    .B(_168_),
    .Y(_006_[6])
  );
  NOR _476_ (
    .A(selector_IDLE),
    .B(dataIn2[7]),
    .Y(_169_)
  );
  NAND _477_ (
    .A(selector_IDLE),
    .B(_066_),
    .Y(_170_)
  );
  NAND _478_ (
    .A(reset),
    .B(_170_),
    .Y(_171_)
  );
  NOR _479_ (
    .A(_169_),
    .B(_171_),
    .Y(_006_[7])
  );
  NOR _480_ (
    .A(selector_IDLE),
    .B(dataIn1[0]),
    .Y(_172_)
  );
  NAND _481_ (
    .A(selector_IDLE),
    .B(_067_),
    .Y(_173_)
  );
  NAND _482_ (
    .A(reset),
    .B(_173_),
    .Y(_174_)
  );
  NOR _483_ (
    .A(_172_),
    .B(_174_),
    .Y(_005_[0])
  );
  NOR _484_ (
    .A(selector_IDLE),
    .B(dataIn1[1]),
    .Y(_175_)
  );
  NAND _485_ (
    .A(selector_IDLE),
    .B(_068_),
    .Y(_176_)
  );
  NAND _486_ (
    .A(reset),
    .B(_176_),
    .Y(_177_)
  );
  NOR _487_ (
    .A(_175_),
    .B(_177_),
    .Y(_005_[1])
  );
  NOR _488_ (
    .A(selector_IDLE),
    .B(dataIn1[2]),
    .Y(_178_)
  );
  NAND _489_ (
    .A(selector_IDLE),
    .B(_069_),
    .Y(_179_)
  );
  NAND _490_ (
    .A(reset),
    .B(_179_),
    .Y(_180_)
  );
  NOR _491_ (
    .A(_178_),
    .B(_180_),
    .Y(_005_[2])
  );
  NOR _492_ (
    .A(selector_IDLE),
    .B(dataIn1[3]),
    .Y(_181_)
  );
  NAND _493_ (
    .A(selector_IDLE),
    .B(_070_),
    .Y(_182_)
  );
  NAND _494_ (
    .A(reset),
    .B(_182_),
    .Y(_183_)
  );
  NOR _495_ (
    .A(_181_),
    .B(_183_),
    .Y(_005_[3])
  );
  NOR _496_ (
    .A(selector_IDLE),
    .B(dataIn1[4]),
    .Y(_184_)
  );
  NAND _497_ (
    .A(selector_IDLE),
    .B(_071_),
    .Y(_185_)
  );
  NAND _498_ (
    .A(reset),
    .B(_185_),
    .Y(_186_)
  );
  NOR _499_ (
    .A(_184_),
    .B(_186_),
    .Y(_005_[4])
  );
  NOR _500_ (
    .A(selector_IDLE),
    .B(dataIn1[5]),
    .Y(_187_)
  );
  NAND _501_ (
    .A(selector_IDLE),
    .B(_072_),
    .Y(_188_)
  );
  NAND _502_ (
    .A(reset),
    .B(_188_),
    .Y(_189_)
  );
  NOR _503_ (
    .A(_187_),
    .B(_189_),
    .Y(_005_[5])
  );
  NOR _504_ (
    .A(selector_IDLE),
    .B(dataIn1[6]),
    .Y(_190_)
  );
  NAND _505_ (
    .A(selector_IDLE),
    .B(_073_),
    .Y(_191_)
  );
  NAND _506_ (
    .A(reset),
    .B(_191_),
    .Y(_192_)
  );
  NOR _507_ (
    .A(_190_),
    .B(_192_),
    .Y(_005_[6])
  );
  NOR _508_ (
    .A(selector_IDLE),
    .B(dataIn1[7]),
    .Y(_193_)
  );
  NAND _509_ (
    .A(selector_IDLE),
    .B(_074_),
    .Y(_194_)
  );
  NAND _510_ (
    .A(reset),
    .B(_194_),
    .Y(_195_)
  );
  NOR _511_ (
    .A(_193_),
    .B(_195_),
    .Y(_005_[7])
  );
  NOR _512_ (
    .A(selector_IDLE),
    .B(dataOut1_synth[0]),
    .Y(_196_)
  );
  NAND _513_ (
    .A(selector_IDLE),
    .B(_035_),
    .Y(_197_)
  );
  NAND _514_ (
    .A(reset),
    .B(_197_),
    .Y(_198_)
  );
  NOR _515_ (
    .A(_196_),
    .B(_198_),
    .Y(_001_[0])
  );
  NOR _516_ (
    .A(selector_IDLE),
    .B(dataOut1_synth[1]),
    .Y(_199_)
  );
  NAND _517_ (
    .A(selector_IDLE),
    .B(_036_),
    .Y(_200_)
  );
  NAND _518_ (
    .A(reset),
    .B(_200_),
    .Y(_201_)
  );
  NOR _519_ (
    .A(_199_),
    .B(_201_),
    .Y(_001_[1])
  );
  NOR _520_ (
    .A(selector_IDLE),
    .B(dataOut1_synth[2]),
    .Y(_202_)
  );
  NAND _521_ (
    .A(selector_IDLE),
    .B(_037_),
    .Y(_203_)
  );
  NAND _522_ (
    .A(reset),
    .B(_203_),
    .Y(_204_)
  );
  NOR _523_ (
    .A(_202_),
    .B(_204_),
    .Y(_001_[2])
  );
  NOR _524_ (
    .A(selector_IDLE),
    .B(dataOut1_synth[3]),
    .Y(_205_)
  );
  NAND _525_ (
    .A(selector_IDLE),
    .B(_038_),
    .Y(_206_)
  );
  NAND _526_ (
    .A(reset),
    .B(_206_),
    .Y(_207_)
  );
  NOR _527_ (
    .A(_205_),
    .B(_207_),
    .Y(_001_[3])
  );
  NOR _528_ (
    .A(selector_IDLE),
    .B(dataOut1_synth[4]),
    .Y(_208_)
  );
  NAND _529_ (
    .A(selector_IDLE),
    .B(_039_),
    .Y(_209_)
  );
  NAND _530_ (
    .A(reset),
    .B(_209_),
    .Y(_210_)
  );
  NOR _531_ (
    .A(_208_),
    .B(_210_),
    .Y(_001_[4])
  );
  NOR _532_ (
    .A(selector_IDLE),
    .B(dataOut1_synth[5]),
    .Y(_211_)
  );
  NAND _533_ (
    .A(selector_IDLE),
    .B(_040_),
    .Y(_212_)
  );
  NAND _534_ (
    .A(reset),
    .B(_212_),
    .Y(_213_)
  );
  NOR _535_ (
    .A(_211_),
    .B(_213_),
    .Y(_001_[5])
  );
  NOR _536_ (
    .A(selector_IDLE),
    .B(dataOut1_synth[6]),
    .Y(_214_)
  );
  NAND _537_ (
    .A(selector_IDLE),
    .B(_041_),
    .Y(_215_)
  );
  NAND _538_ (
    .A(reset),
    .B(_215_),
    .Y(_216_)
  );
  NOR _539_ (
    .A(_214_),
    .B(_216_),
    .Y(_001_[6])
  );
  NOR _540_ (
    .A(selector_IDLE),
    .B(dataOut1_synth[7]),
    .Y(_217_)
  );
  NAND _541_ (
    .A(selector_IDLE),
    .B(_042_),
    .Y(_218_)
  );
  NAND _542_ (
    .A(reset),
    .B(_218_),
    .Y(_219_)
  );
  NOR _543_ (
    .A(_217_),
    .B(_219_),
    .Y(_001_[7])
  );
  NOR _544_ (
    .A(selector_IDLE),
    .B(dataOut3_synth[0]),
    .Y(_220_)
  );
  NAND _545_ (
    .A(selector_IDLE),
    .B(_019_),
    .Y(_221_)
  );
  NAND _546_ (
    .A(reset),
    .B(_221_),
    .Y(_222_)
  );
  NOR _547_ (
    .A(_220_),
    .B(_222_),
    .Y(_003_[0])
  );
  NOR _548_ (
    .A(selector_IDLE),
    .B(dataOut3_synth[1]),
    .Y(_223_)
  );
  NAND _549_ (
    .A(selector_IDLE),
    .B(_020_),
    .Y(_224_)
  );
  NAND _550_ (
    .A(reset),
    .B(_224_),
    .Y(_225_)
  );
  NOR _551_ (
    .A(_223_),
    .B(_225_),
    .Y(_003_[1])
  );
  NOR _552_ (
    .A(selector_IDLE),
    .B(dataOut3_synth[2]),
    .Y(_226_)
  );
  NAND _553_ (
    .A(selector_IDLE),
    .B(_021_),
    .Y(_227_)
  );
  NAND _554_ (
    .A(reset),
    .B(_227_),
    .Y(_228_)
  );
  NOR _555_ (
    .A(_226_),
    .B(_228_),
    .Y(_003_[2])
  );
  NOR _556_ (
    .A(selector_IDLE),
    .B(dataOut3_synth[3]),
    .Y(_229_)
  );
  NAND _557_ (
    .A(selector_IDLE),
    .B(_022_),
    .Y(_230_)
  );
  NAND _558_ (
    .A(reset),
    .B(_230_),
    .Y(_231_)
  );
  NOR _559_ (
    .A(_229_),
    .B(_231_),
    .Y(_003_[3])
  );
  NOR _560_ (
    .A(selector_IDLE),
    .B(dataOut3_synth[4]),
    .Y(_232_)
  );
  NAND _561_ (
    .A(selector_IDLE),
    .B(_023_),
    .Y(_233_)
  );
  NAND _562_ (
    .A(reset),
    .B(_233_),
    .Y(_234_)
  );
  NOR _563_ (
    .A(_232_),
    .B(_234_),
    .Y(_003_[4])
  );
  NOR _564_ (
    .A(selector_IDLE),
    .B(dataOut3_synth[5]),
    .Y(_235_)
  );
  NAND _565_ (
    .A(selector_IDLE),
    .B(_024_),
    .Y(_236_)
  );
  NAND _566_ (
    .A(reset),
    .B(_236_),
    .Y(_237_)
  );
  NOR _567_ (
    .A(_235_),
    .B(_237_),
    .Y(_003_[5])
  );
  NOR _568_ (
    .A(selector_IDLE),
    .B(dataOut3_synth[6]),
    .Y(_238_)
  );
  NAND _569_ (
    .A(selector_IDLE),
    .B(_025_),
    .Y(_239_)
  );
  NAND _570_ (
    .A(reset),
    .B(_239_),
    .Y(_240_)
  );
  NOR _571_ (
    .A(_238_),
    .B(_240_),
    .Y(_003_[6])
  );
  NOR _572_ (
    .A(selector_IDLE),
    .B(dataOut3_synth[7]),
    .Y(_241_)
  );
  NAND _573_ (
    .A(selector_IDLE),
    .B(_026_),
    .Y(_242_)
  );
  NAND _574_ (
    .A(reset),
    .B(_242_),
    .Y(_243_)
  );
  NOR _575_ (
    .A(_241_),
    .B(_243_),
    .Y(_003_[7])
  );
  NOR _576_ (
    .A(selector_IDLE),
    .B(dataOut2_synth[0]),
    .Y(_244_)
  );
  NAND _577_ (
    .A(selector_IDLE),
    .B(_027_),
    .Y(_245_)
  );
  NAND _578_ (
    .A(reset),
    .B(_245_),
    .Y(_246_)
  );
  NOR _579_ (
    .A(_244_),
    .B(_246_),
    .Y(_002_[0])
  );
  NOR _580_ (
    .A(selector_IDLE),
    .B(dataOut2_synth[1]),
    .Y(_247_)
  );
  NAND _581_ (
    .A(selector_IDLE),
    .B(_028_),
    .Y(_248_)
  );
  NAND _582_ (
    .A(reset),
    .B(_248_),
    .Y(_249_)
  );
  NOR _583_ (
    .A(_247_),
    .B(_249_),
    .Y(_002_[1])
  );
  NOR _584_ (
    .A(selector_IDLE),
    .B(dataOut2_synth[2]),
    .Y(_250_)
  );
  NAND _585_ (
    .A(selector_IDLE),
    .B(_029_),
    .Y(_251_)
  );
  NAND _586_ (
    .A(reset),
    .B(_251_),
    .Y(_252_)
  );
  NOR _587_ (
    .A(_250_),
    .B(_252_),
    .Y(_002_[2])
  );
  NOR _588_ (
    .A(selector_IDLE),
    .B(dataOut2_synth[3]),
    .Y(_253_)
  );
  NAND _589_ (
    .A(selector_IDLE),
    .B(_030_),
    .Y(_254_)
  );
  NAND _590_ (
    .A(reset),
    .B(_254_),
    .Y(_255_)
  );
  NOR _591_ (
    .A(_253_),
    .B(_255_),
    .Y(_002_[3])
  );
  NOR _592_ (
    .A(selector_IDLE),
    .B(dataOut2_synth[4]),
    .Y(_256_)
  );
  NAND _593_ (
    .A(selector_IDLE),
    .B(_031_),
    .Y(_257_)
  );
  NAND _594_ (
    .A(reset),
    .B(_257_),
    .Y(_258_)
  );
  NOR _595_ (
    .A(_256_),
    .B(_258_),
    .Y(_002_[4])
  );
  NOR _596_ (
    .A(selector_IDLE),
    .B(dataOut2_synth[5]),
    .Y(_259_)
  );
  NAND _597_ (
    .A(selector_IDLE),
    .B(_032_),
    .Y(_260_)
  );
  NAND _598_ (
    .A(reset),
    .B(_260_),
    .Y(_261_)
  );
  NOR _599_ (
    .A(_259_),
    .B(_261_),
    .Y(_002_[5])
  );
  NOR _600_ (
    .A(selector_IDLE),
    .B(dataOut2_synth[6]),
    .Y(_262_)
  );
  NAND _601_ (
    .A(selector_IDLE),
    .B(_033_),
    .Y(_263_)
  );
  NAND _602_ (
    .A(reset),
    .B(_263_),
    .Y(_264_)
  );
  NOR _603_ (
    .A(_262_),
    .B(_264_),
    .Y(_002_[6])
  );
  NOR _604_ (
    .A(selector_IDLE),
    .B(dataOut2_synth[7]),
    .Y(_265_)
  );
  NAND _605_ (
    .A(selector_IDLE),
    .B(_034_),
    .Y(_266_)
  );
  NAND _606_ (
    .A(reset),
    .B(_266_),
    .Y(_267_)
  );
  NOR _607_ (
    .A(_265_),
    .B(_267_),
    .Y(_002_[7])
  );
  NOR _608_ (
    .A(selector_IDLE),
    .B(dataOut0_synth[0]),
    .Y(_268_)
  );
  NAND _609_ (
    .A(selector_IDLE),
    .B(_043_),
    .Y(_269_)
  );
  NAND _610_ (
    .A(reset),
    .B(_269_),
    .Y(_270_)
  );
  NOR _611_ (
    .A(_268_),
    .B(_270_),
    .Y(_000_[0])
  );
  NOR _612_ (
    .A(selector_IDLE),
    .B(dataOut0_synth[1]),
    .Y(_271_)
  );
  NAND _613_ (
    .A(selector_IDLE),
    .B(_044_),
    .Y(_272_)
  );
  NAND _614_ (
    .A(reset),
    .B(_272_),
    .Y(_273_)
  );
  NOR _615_ (
    .A(_271_),
    .B(_273_),
    .Y(_000_[1])
  );
  NOR _616_ (
    .A(selector_IDLE),
    .B(dataOut0_synth[2]),
    .Y(_274_)
  );
  NAND _617_ (
    .A(selector_IDLE),
    .B(_045_),
    .Y(_275_)
  );
  NAND _618_ (
    .A(reset),
    .B(_275_),
    .Y(_276_)
  );
  NOR _619_ (
    .A(_274_),
    .B(_276_),
    .Y(_000_[2])
  );
  NOR _620_ (
    .A(selector_IDLE),
    .B(dataOut0_synth[3]),
    .Y(_277_)
  );
  NAND _621_ (
    .A(selector_IDLE),
    .B(_046_),
    .Y(_278_)
  );
  NAND _622_ (
    .A(reset),
    .B(_278_),
    .Y(_279_)
  );
  NOR _623_ (
    .A(_277_),
    .B(_279_),
    .Y(_000_[3])
  );
  NOR _624_ (
    .A(selector_IDLE),
    .B(dataOut0_synth[4]),
    .Y(_280_)
  );
  NAND _625_ (
    .A(selector_IDLE),
    .B(_047_),
    .Y(_281_)
  );
  NAND _626_ (
    .A(reset),
    .B(_281_),
    .Y(_282_)
  );
  NOR _627_ (
    .A(_280_),
    .B(_282_),
    .Y(_000_[4])
  );
  NOR _628_ (
    .A(selector_IDLE),
    .B(dataOut0_synth[5]),
    .Y(_283_)
  );
  NAND _629_ (
    .A(selector_IDLE),
    .B(_048_),
    .Y(_284_)
  );
  NAND _630_ (
    .A(reset),
    .B(_284_),
    .Y(_285_)
  );
  NOR _631_ (
    .A(_283_),
    .B(_285_),
    .Y(_000_[5])
  );
  NOR _632_ (
    .A(selector_IDLE),
    .B(dataOut0_synth[6]),
    .Y(_286_)
  );
  NAND _633_ (
    .A(selector_IDLE),
    .B(_049_),
    .Y(_287_)
  );
  NAND _634_ (
    .A(reset),
    .B(_287_),
    .Y(_288_)
  );
  NOR _635_ (
    .A(_286_),
    .B(_288_),
    .Y(_000_[6])
  );
  NOR _636_ (
    .A(selector_IDLE),
    .B(dataOut0_synth[7]),
    .Y(_289_)
  );
  NAND _637_ (
    .A(selector_IDLE),
    .B(_050_),
    .Y(_290_)
  );
  NAND _638_ (
    .A(reset),
    .B(_290_),
    .Y(_291_)
  );
  NOR _639_ (
    .A(_289_),
    .B(_291_),
    .Y(_000_[7])
  );
  (* src = "Recirculador_sintetizado.v:107" *)
  DFF _640_ (
    .C(selector_IDLE),
    .D(dataIn0[0]),
    .Q(dataOut4_synth[0])
  );
  (* src = "Recirculador_sintetizado.v:107" *)
  DFF _641_ (
    .C(selector_IDLE),
    .D(dataIn0[1]),
    .Q(dataOut4_synth[1])
  );
  (* src = "Recirculador_sintetizado.v:107" *)
  DFF _642_ (
    .C(selector_IDLE),
    .D(dataIn0[2]),
    .Q(dataOut4_synth[2])
  );
  (* src = "Recirculador_sintetizado.v:107" *)
  DFF _643_ (
    .C(selector_IDLE),
    .D(dataIn0[3]),
    .Q(dataOut4_synth[3])
  );
  (* src = "Recirculador_sintetizado.v:107" *)
  DFF _644_ (
    .C(selector_IDLE),
    .D(dataIn0[4]),
    .Q(dataOut4_synth[4])
  );
  (* src = "Recirculador_sintetizado.v:107" *)
  DFF _645_ (
    .C(selector_IDLE),
    .D(dataIn0[5]),
    .Q(dataOut4_synth[5])
  );
  (* src = "Recirculador_sintetizado.v:107" *)
  DFF _646_ (
    .C(selector_IDLE),
    .D(dataIn0[6]),
    .Q(dataOut4_synth[6])
  );
  (* src = "Recirculador_sintetizado.v:107" *)
  DFF _647_ (
    .C(selector_IDLE),
    .D(dataIn0[7]),
    .Q(dataOut4_synth[7])
  );
  (* src = "Recirculador_sintetizado.v:107" *)
  DFF _648_ (
    .C(selector_IDLE),
    .D(dataIn1[0]),
    .Q(dataOut5_synth[0])
  );
  (* src = "Recirculador_sintetizado.v:107" *)
  DFF _649_ (
    .C(selector_IDLE),
    .D(dataIn1[1]),
    .Q(dataOut5_synth[1])
  );
  (* src = "Recirculador_sintetizado.v:107" *)
  DFF _650_ (
    .C(selector_IDLE),
    .D(dataIn1[2]),
    .Q(dataOut5_synth[2])
  );
  (* src = "Recirculador_sintetizado.v:107" *)
  DFF _651_ (
    .C(selector_IDLE),
    .D(dataIn1[3]),
    .Q(dataOut5_synth[3])
  );
  (* src = "Recirculador_sintetizado.v:107" *)
  DFF _652_ (
    .C(selector_IDLE),
    .D(dataIn1[4]),
    .Q(dataOut5_synth[4])
  );
  (* src = "Recirculador_sintetizado.v:107" *)
  DFF _653_ (
    .C(selector_IDLE),
    .D(dataIn1[5]),
    .Q(dataOut5_synth[5])
  );
  (* src = "Recirculador_sintetizado.v:107" *)
  DFF _654_ (
    .C(selector_IDLE),
    .D(dataIn1[6]),
    .Q(dataOut5_synth[6])
  );
  (* src = "Recirculador_sintetizado.v:107" *)
  DFF _655_ (
    .C(selector_IDLE),
    .D(dataIn1[7]),
    .Q(dataOut5_synth[7])
  );
  (* src = "Recirculador_sintetizado.v:107" *)
  DFF _656_ (
    .C(selector_IDLE),
    .D(dataIn2[0]),
    .Q(dataOut6_synth[0])
  );
  (* src = "Recirculador_sintetizado.v:107" *)
  DFF _657_ (
    .C(selector_IDLE),
    .D(dataIn2[1]),
    .Q(dataOut6_synth[1])
  );
  (* src = "Recirculador_sintetizado.v:107" *)
  DFF _658_ (
    .C(selector_IDLE),
    .D(dataIn2[2]),
    .Q(dataOut6_synth[2])
  );
  (* src = "Recirculador_sintetizado.v:107" *)
  DFF _659_ (
    .C(selector_IDLE),
    .D(dataIn2[3]),
    .Q(dataOut6_synth[3])
  );
  (* src = "Recirculador_sintetizado.v:107" *)
  DFF _660_ (
    .C(selector_IDLE),
    .D(dataIn2[4]),
    .Q(dataOut6_synth[4])
  );
  (* src = "Recirculador_sintetizado.v:107" *)
  DFF _661_ (
    .C(selector_IDLE),
    .D(dataIn2[5]),
    .Q(dataOut6_synth[5])
  );
  (* src = "Recirculador_sintetizado.v:107" *)
  DFF _662_ (
    .C(selector_IDLE),
    .D(dataIn2[6]),
    .Q(dataOut6_synth[6])
  );
  (* src = "Recirculador_sintetizado.v:107" *)
  DFF _663_ (
    .C(selector_IDLE),
    .D(dataIn2[7]),
    .Q(dataOut6_synth[7])
  );
  (* src = "Recirculador_sintetizado.v:107" *)
  DFF _664_ (
    .C(selector_IDLE),
    .D(dataIn3[0]),
    .Q(dataOut7_synth[0])
  );
  (* src = "Recirculador_sintetizado.v:107" *)
  DFF _665_ (
    .C(selector_IDLE),
    .D(dataIn3[1]),
    .Q(dataOut7_synth[1])
  );
  (* src = "Recirculador_sintetizado.v:107" *)
  DFF _666_ (
    .C(selector_IDLE),
    .D(dataIn3[2]),
    .Q(dataOut7_synth[2])
  );
  (* src = "Recirculador_sintetizado.v:107" *)
  DFF _667_ (
    .C(selector_IDLE),
    .D(dataIn3[3]),
    .Q(dataOut7_synth[3])
  );
  (* src = "Recirculador_sintetizado.v:107" *)
  DFF _668_ (
    .C(selector_IDLE),
    .D(dataIn3[4]),
    .Q(dataOut7_synth[4])
  );
  (* src = "Recirculador_sintetizado.v:107" *)
  DFF _669_ (
    .C(selector_IDLE),
    .D(dataIn3[5]),
    .Q(dataOut7_synth[5])
  );
  (* src = "Recirculador_sintetizado.v:107" *)
  DFF _670_ (
    .C(selector_IDLE),
    .D(dataIn3[6]),
    .Q(dataOut7_synth[6])
  );
  (* src = "Recirculador_sintetizado.v:107" *)
  DFF _671_ (
    .C(selector_IDLE),
    .D(dataIn3[7]),
    .Q(dataOut7_synth[7])
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _672_ (
    .C(clk),
    .D(_000_[0]),
    .Q(dataOut0_synth[0])
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _673_ (
    .C(clk),
    .D(_000_[1]),
    .Q(dataOut0_synth[1])
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _674_ (
    .C(clk),
    .D(_000_[2]),
    .Q(dataOut0_synth[2])
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _675_ (
    .C(clk),
    .D(_000_[3]),
    .Q(dataOut0_synth[3])
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _676_ (
    .C(clk),
    .D(_000_[4]),
    .Q(dataOut0_synth[4])
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _677_ (
    .C(clk),
    .D(_000_[5]),
    .Q(dataOut0_synth[5])
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _678_ (
    .C(clk),
    .D(_000_[6]),
    .Q(dataOut0_synth[6])
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _679_ (
    .C(clk),
    .D(_000_[7]),
    .Q(dataOut0_synth[7])
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _680_ (
    .C(clk),
    .D(_001_[0]),
    .Q(dataOut1_synth[0])
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _681_ (
    .C(clk),
    .D(_001_[1]),
    .Q(dataOut1_synth[1])
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _682_ (
    .C(clk),
    .D(_001_[2]),
    .Q(dataOut1_synth[2])
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _683_ (
    .C(clk),
    .D(_001_[3]),
    .Q(dataOut1_synth[3])
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _684_ (
    .C(clk),
    .D(_001_[4]),
    .Q(dataOut1_synth[4])
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _685_ (
    .C(clk),
    .D(_001_[5]),
    .Q(dataOut1_synth[5])
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _686_ (
    .C(clk),
    .D(_001_[6]),
    .Q(dataOut1_synth[6])
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _687_ (
    .C(clk),
    .D(_001_[7]),
    .Q(dataOut1_synth[7])
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _688_ (
    .C(clk),
    .D(_002_[0]),
    .Q(dataOut2_synth[0])
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _689_ (
    .C(clk),
    .D(_002_[1]),
    .Q(dataOut2_synth[1])
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _690_ (
    .C(clk),
    .D(_002_[2]),
    .Q(dataOut2_synth[2])
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _691_ (
    .C(clk),
    .D(_002_[3]),
    .Q(dataOut2_synth[3])
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _692_ (
    .C(clk),
    .D(_002_[4]),
    .Q(dataOut2_synth[4])
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _693_ (
    .C(clk),
    .D(_002_[5]),
    .Q(dataOut2_synth[5])
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _694_ (
    .C(clk),
    .D(_002_[6]),
    .Q(dataOut2_synth[6])
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _695_ (
    .C(clk),
    .D(_002_[7]),
    .Q(dataOut2_synth[7])
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _696_ (
    .C(clk),
    .D(_003_[0]),
    .Q(dataOut3_synth[0])
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _697_ (
    .C(clk),
    .D(_003_[1]),
    .Q(dataOut3_synth[1])
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _698_ (
    .C(clk),
    .D(_003_[2]),
    .Q(dataOut3_synth[2])
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _699_ (
    .C(clk),
    .D(_003_[3]),
    .Q(dataOut3_synth[3])
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _700_ (
    .C(clk),
    .D(_003_[4]),
    .Q(dataOut3_synth[4])
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _701_ (
    .C(clk),
    .D(_003_[5]),
    .Q(dataOut3_synth[5])
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _702_ (
    .C(clk),
    .D(_003_[6]),
    .Q(dataOut3_synth[6])
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _703_ (
    .C(clk),
    .D(_003_[7]),
    .Q(dataOut3_synth[7])
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _704_ (
    .C(clk),
    .D(_004_[0]),
    .Q(dataOut4_synth[0])
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _705_ (
    .C(clk),
    .D(_004_[1]),
    .Q(dataOut4_synth[1])
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _706_ (
    .C(clk),
    .D(_004_[2]),
    .Q(dataOut4_synth[2])
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _707_ (
    .C(clk),
    .D(_004_[3]),
    .Q(dataOut4_synth[3])
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _708_ (
    .C(clk),
    .D(_004_[4]),
    .Q(dataOut4_synth[4])
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _709_ (
    .C(clk),
    .D(_004_[5]),
    .Q(dataOut4_synth[5])
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _710_ (
    .C(clk),
    .D(_004_[6]),
    .Q(dataOut4_synth[6])
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _711_ (
    .C(clk),
    .D(_004_[7]),
    .Q(dataOut4_synth[7])
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _712_ (
    .C(clk),
    .D(_005_[0]),
    .Q(dataOut5_synth[0])
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _713_ (
    .C(clk),
    .D(_005_[1]),
    .Q(dataOut5_synth[1])
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _714_ (
    .C(clk),
    .D(_005_[2]),
    .Q(dataOut5_synth[2])
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _715_ (
    .C(clk),
    .D(_005_[3]),
    .Q(dataOut5_synth[3])
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _716_ (
    .C(clk),
    .D(_005_[4]),
    .Q(dataOut5_synth[4])
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _717_ (
    .C(clk),
    .D(_005_[5]),
    .Q(dataOut5_synth[5])
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _718_ (
    .C(clk),
    .D(_005_[6]),
    .Q(dataOut5_synth[6])
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _719_ (
    .C(clk),
    .D(_005_[7]),
    .Q(dataOut5_synth[7])
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _720_ (
    .C(clk),
    .D(_006_[0]),
    .Q(dataOut6_synth[0])
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _721_ (
    .C(clk),
    .D(_006_[1]),
    .Q(dataOut6_synth[1])
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _722_ (
    .C(clk),
    .D(_006_[2]),
    .Q(dataOut6_synth[2])
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _723_ (
    .C(clk),
    .D(_006_[3]),
    .Q(dataOut6_synth[3])
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _724_ (
    .C(clk),
    .D(_006_[4]),
    .Q(dataOut6_synth[4])
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _725_ (
    .C(clk),
    .D(_006_[5]),
    .Q(dataOut6_synth[5])
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _726_ (
    .C(clk),
    .D(_006_[6]),
    .Q(dataOut6_synth[6])
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _727_ (
    .C(clk),
    .D(_006_[7]),
    .Q(dataOut6_synth[7])
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _728_ (
    .C(clk),
    .D(_007_[0]),
    .Q(dataOut7_synth[0])
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _729_ (
    .C(clk),
    .D(_007_[1]),
    .Q(dataOut7_synth[1])
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _730_ (
    .C(clk),
    .D(_007_[2]),
    .Q(dataOut7_synth[2])
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _731_ (
    .C(clk),
    .D(_007_[3]),
    .Q(dataOut7_synth[3])
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _732_ (
    .C(clk),
    .D(_007_[4]),
    .Q(dataOut7_synth[4])
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _733_ (
    .C(clk),
    .D(_007_[5]),
    .Q(dataOut7_synth[5])
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _734_ (
    .C(clk),
    .D(_007_[6]),
    .Q(dataOut7_synth[6])
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _735_ (
    .C(clk),
    .D(_007_[7]),
    .Q(dataOut7_synth[7])
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _736_ (
    .C(clk),
    .D(_008_),
    .Q(validOut0_synth)
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _737_ (
    .C(clk),
    .D(_009_),
    .Q(validOut1_synth)
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _738_ (
    .C(clk),
    .D(_010_),
    .Q(validOut2_synth)
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _739_ (
    .C(clk),
    .D(_011_),
    .Q(validOut3_synth)
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _740_ (
    .C(clk),
    .D(_012_),
    .Q(validOut4_synth)
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _741_ (
    .C(clk),
    .D(_013_),
    .Q(validOut5_synth)
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _742_ (
    .C(clk),
    .D(_014_),
    .Q(validOut6_synth)
  );
  (* src = "Recirculador_sintetizado.v:32" *)
  DFF _743_ (
    .C(clk),
    .D(_015_),
    .Q(validOut7_synth)
  );
endmodule
