/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "SerialParalelo_PhyTX.v:1" *)
module SerialParalelo_PhyTX_Synth(clk_1, clk_2, reset, IDLE_in, IDLE_out_cond);
  (* src = "SerialParalelo_PhyTX.v:57" *)
  wire _000_;
  (* src = "SerialParalelo_PhyTX.v:21" *)
  wire [2:0] _001_;
  (* src = "SerialParalelo_PhyTX.v:21" *)
  wire [2:0] _002_;
  (* src = "SerialParalelo_PhyTX.v:21" *)
  wire [7:0] _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  (* src = "SerialParalelo_PhyTX.v:5" *)
  input IDLE_in;
  (* src = "SerialParalelo_PhyTX.v:6" *)
  output IDLE_out_cond;
  (* src = "SerialParalelo_PhyTX.v:9" *)
  wire active;
  (* src = "SerialParalelo_PhyTX.v:2" *)
  input clk_1;
  (* src = "SerialParalelo_PhyTX.v:3" *)
  input clk_2;
  (* init = 3'h0 *)
  (* src = "SerialParalelo_PhyTX.v:10" *)
  wire [2:0] contador_COM;
  (* src = "SerialParalelo_PhyTX.v:4" *)
  input reset;
  (* init = 3'h0 *)
  (* src = "SerialParalelo_PhyTX.v:13" *)
  wire [2:0] selector;
  (* src = "SerialParalelo_PhyTX.v:12" *)
  wire [7:0] temporal;
  (* src = "SerialParalelo_PhyTX.v:11" *)
  wire x7C;
  NOT _079_ (
    .A(selector[0]),
    .Y(_020_)
  );
  NOT _080_ (
    .A(selector[1]),
    .Y(_021_)
  );
  NOT _081_ (
    .A(selector[2]),
    .Y(_022_)
  );
  NOT _082_ (
    .A(contador_COM[2]),
    .Y(_023_)
  );
  NOT _083_ (
    .A(reset),
    .Y(_024_)
  );
  NOR _084_ (
    .A(selector[0]),
    .B(_021_),
    .Y(_025_)
  );
  NAND _085_ (
    .A(_020_),
    .B(selector[1]),
    .Y(_026_)
  );
  NOR _086_ (
    .A(_022_),
    .B(_024_),
    .Y(_027_)
  );
  NAND _087_ (
    .A(selector[2]),
    .B(reset),
    .Y(_028_)
  );
  NOR _088_ (
    .A(_026_),
    .B(_028_),
    .Y(_029_)
  );
  NAND _089_ (
    .A(_025_),
    .B(_027_),
    .Y(_030_)
  );
  NAND _090_ (
    .A(IDLE_in),
    .B(_029_),
    .Y(_031_)
  );
  NAND _091_ (
    .A(temporal[1]),
    .B(_030_),
    .Y(_032_)
  );
  NAND _092_ (
    .A(_031_),
    .B(_032_),
    .Y(_003_[1])
  );
  NOR _093_ (
    .A(_020_),
    .B(_021_),
    .Y(_033_)
  );
  NAND _094_ (
    .A(selector[0]),
    .B(selector[1]),
    .Y(_034_)
  );
  NOR _095_ (
    .A(_028_),
    .B(_034_),
    .Y(_035_)
  );
  NOT _096_ (
    .A(_035_),
    .Y(_036_)
  );
  NAND _097_ (
    .A(IDLE_in),
    .B(_035_),
    .Y(_037_)
  );
  NAND _098_ (
    .A(temporal[0]),
    .B(_036_),
    .Y(_038_)
  );
  NAND _099_ (
    .A(_037_),
    .B(_038_),
    .Y(_003_[0])
  );
  NOR _100_ (
    .A(_020_),
    .B(selector[1]),
    .Y(_039_)
  );
  NAND _101_ (
    .A(selector[0]),
    .B(_021_),
    .Y(_040_)
  );
  NOR _102_ (
    .A(_028_),
    .B(_040_),
    .Y(_041_)
  );
  NAND _103_ (
    .A(_027_),
    .B(_039_),
    .Y(_042_)
  );
  NAND _104_ (
    .A(IDLE_in),
    .B(_041_),
    .Y(_043_)
  );
  NAND _105_ (
    .A(temporal[2]),
    .B(_042_),
    .Y(_044_)
  );
  NAND _106_ (
    .A(_043_),
    .B(_044_),
    .Y(_003_[2])
  );
  NOR _107_ (
    .A(selector[0]),
    .B(selector[1]),
    .Y(_045_)
  );
  NOT _108_ (
    .A(_045_),
    .Y(_046_)
  );
  NOR _109_ (
    .A(_028_),
    .B(_046_),
    .Y(_047_)
  );
  NAND _110_ (
    .A(_027_),
    .B(_045_),
    .Y(_048_)
  );
  NAND _111_ (
    .A(IDLE_in),
    .B(_047_),
    .Y(_049_)
  );
  NAND _112_ (
    .A(temporal[3]),
    .B(_048_),
    .Y(_050_)
  );
  NAND _113_ (
    .A(_049_),
    .B(_050_),
    .Y(_003_[3])
  );
  NOR _114_ (
    .A(selector[2]),
    .B(_024_),
    .Y(_051_)
  );
  NAND _115_ (
    .A(_022_),
    .B(reset),
    .Y(_052_)
  );
  NOR _116_ (
    .A(_034_),
    .B(_052_),
    .Y(_053_)
  );
  NAND _117_ (
    .A(_033_),
    .B(_051_),
    .Y(_054_)
  );
  NAND _118_ (
    .A(IDLE_in),
    .B(_053_),
    .Y(_055_)
  );
  NAND _119_ (
    .A(temporal[4]),
    .B(_054_),
    .Y(_056_)
  );
  NAND _120_ (
    .A(_055_),
    .B(_056_),
    .Y(_003_[4])
  );
  NOR _121_ (
    .A(_026_),
    .B(_052_),
    .Y(_057_)
  );
  NAND _122_ (
    .A(_025_),
    .B(_051_),
    .Y(_058_)
  );
  NAND _123_ (
    .A(IDLE_in),
    .B(_057_),
    .Y(_059_)
  );
  NAND _124_ (
    .A(temporal[5]),
    .B(_058_),
    .Y(_060_)
  );
  NAND _125_ (
    .A(_059_),
    .B(_060_),
    .Y(_003_[5])
  );
  NOR _126_ (
    .A(_040_),
    .B(_052_),
    .Y(_061_)
  );
  NAND _127_ (
    .A(_039_),
    .B(_051_),
    .Y(_062_)
  );
  NAND _128_ (
    .A(IDLE_in),
    .B(_061_),
    .Y(_063_)
  );
  NAND _129_ (
    .A(temporal[6]),
    .B(_062_),
    .Y(_064_)
  );
  NAND _130_ (
    .A(_063_),
    .B(_064_),
    .Y(_003_[6])
  );
  NOR _131_ (
    .A(_046_),
    .B(_052_),
    .Y(_065_)
  );
  NAND _132_ (
    .A(_045_),
    .B(_051_),
    .Y(_066_)
  );
  NAND _133_ (
    .A(IDLE_in),
    .B(_065_),
    .Y(_067_)
  );
  NAND _134_ (
    .A(temporal[7]),
    .B(_066_),
    .Y(_068_)
  );
  NAND _135_ (
    .A(_067_),
    .B(_068_),
    .Y(_003_[7])
  );
  NAND _136_ (
    .A(temporal[7]),
    .B(selector[2]),
    .Y(_069_)
  );
  NOR _137_ (
    .A(temporal[6]),
    .B(_069_),
    .Y(_070_)
  );
  NAND _138_ (
    .A(_033_),
    .B(_070_),
    .Y(_071_)
  );
  NOR _139_ (
    .A(contador_COM[2]),
    .B(_071_),
    .Y(_072_)
  );
  NAND _140_ (
    .A(contador_COM[0]),
    .B(_072_),
    .Y(_073_)
  );
  NOT _141_ (
    .A(_073_),
    .Y(_074_)
  );
  NOR _142_ (
    .A(contador_COM[0]),
    .B(_072_),
    .Y(_075_)
  );
  NOT _143_ (
    .A(_075_),
    .Y(_076_)
  );
  NAND _144_ (
    .A(reset),
    .B(_076_),
    .Y(_077_)
  );
  NOR _145_ (
    .A(_074_),
    .B(_077_),
    .Y(_001_[0])
  );
  NOR _146_ (
    .A(contador_COM[1]),
    .B(_074_),
    .Y(_078_)
  );
  NAND _147_ (
    .A(contador_COM[0]),
    .B(contador_COM[1]),
    .Y(_004_)
  );
  NOR _148_ (
    .A(_071_),
    .B(_004_),
    .Y(_005_)
  );
  NAND _149_ (
    .A(_023_),
    .B(_005_),
    .Y(_006_)
  );
  NAND _150_ (
    .A(reset),
    .B(_006_),
    .Y(_007_)
  );
  NOR _151_ (
    .A(_078_),
    .B(_007_),
    .Y(_001_[1])
  );
  NOR _152_ (
    .A(contador_COM[2]),
    .B(_005_),
    .Y(_008_)
  );
  NOR _153_ (
    .A(_024_),
    .B(_008_),
    .Y(_001_[2])
  );
  NOR _154_ (
    .A(selector[0]),
    .B(_024_),
    .Y(_002_[0])
  );
  NAND _155_ (
    .A(reset),
    .B(_034_),
    .Y(_009_)
  );
  NOR _156_ (
    .A(_045_),
    .B(_009_),
    .Y(_002_[1])
  );
  NAND _157_ (
    .A(_027_),
    .B(_034_),
    .Y(_010_)
  );
  NAND _158_ (
    .A(_054_),
    .B(_010_),
    .Y(_002_[2])
  );
  NAND _159_ (
    .A(temporal[4]),
    .B(temporal[5]),
    .Y(_011_)
  );
  NOT _160_ (
    .A(_011_),
    .Y(_012_)
  );
  NAND _161_ (
    .A(temporal[6]),
    .B(_012_),
    .Y(_013_)
  );
  NOR _162_ (
    .A(temporal[7]),
    .B(_023_),
    .Y(_014_)
  );
  NOR _163_ (
    .A(temporal[1]),
    .B(temporal[0]),
    .Y(_015_)
  );
  NOT _164_ (
    .A(_015_),
    .Y(_016_)
  );
  NAND _165_ (
    .A(temporal[2]),
    .B(temporal[3]),
    .Y(_017_)
  );
  NOR _166_ (
    .A(_016_),
    .B(_017_),
    .Y(_018_)
  );
  NAND _167_ (
    .A(_014_),
    .B(_018_),
    .Y(_019_)
  );
  NOR _168_ (
    .A(_013_),
    .B(_019_),
    .Y(_000_)
  );
  (* src = "SerialParalelo_PhyTX.v:57" *)
  DFF _169_ (
    .C(clk_2),
    .D(_000_),
    .Q(IDLE_out_cond)
  );
  (* src = "SerialParalelo_PhyTX.v:21" *)
  DFF _170_ (
    .C(clk_1),
    .D(_001_[0]),
    .Q(contador_COM[0])
  );
  (* src = "SerialParalelo_PhyTX.v:21" *)
  DFF _171_ (
    .C(clk_1),
    .D(_001_[1]),
    .Q(contador_COM[1])
  );
  (* src = "SerialParalelo_PhyTX.v:21" *)
  DFF _172_ (
    .C(clk_1),
    .D(_001_[2]),
    .Q(contador_COM[2])
  );
  (* src = "SerialParalelo_PhyTX.v:21" *)
  DFF _173_ (
    .C(clk_1),
    .D(_003_[0]),
    .Q(temporal[0])
  );
  (* src = "SerialParalelo_PhyTX.v:21" *)
  DFF _174_ (
    .C(clk_1),
    .D(_003_[1]),
    .Q(temporal[1])
  );
  (* src = "SerialParalelo_PhyTX.v:21" *)
  DFF _175_ (
    .C(clk_1),
    .D(_003_[2]),
    .Q(temporal[2])
  );
  (* src = "SerialParalelo_PhyTX.v:21" *)
  DFF _176_ (
    .C(clk_1),
    .D(_003_[3]),
    .Q(temporal[3])
  );
  (* src = "SerialParalelo_PhyTX.v:21" *)
  DFF _177_ (
    .C(clk_1),
    .D(_003_[4]),
    .Q(temporal[4])
  );
  (* src = "SerialParalelo_PhyTX.v:21" *)
  DFF _178_ (
    .C(clk_1),
    .D(_003_[5]),
    .Q(temporal[5])
  );
  (* src = "SerialParalelo_PhyTX.v:21" *)
  DFF _179_ (
    .C(clk_1),
    .D(_003_[6]),
    .Q(temporal[6])
  );
  (* src = "SerialParalelo_PhyTX.v:21" *)
  DFF _180_ (
    .C(clk_1),
    .D(_003_[7]),
    .Q(temporal[7])
  );
  (* src = "SerialParalelo_PhyTX.v:21" *)
  DFF _181_ (
    .C(clk_1),
    .D(_002_[0]),
    .Q(selector[0])
  );
  (* src = "SerialParalelo_PhyTX.v:21" *)
  DFF _182_ (
    .C(clk_1),
    .D(_002_[1]),
    .Q(selector[1])
  );
  (* src = "SerialParalelo_PhyTX.v:21" *)
  DFF _183_ (
    .C(clk_1),
    .D(_002_[2]),
    .Q(selector[2])
  );
  assign active = 1'h0;
  assign x7C = 1'h0;
endmodule
