/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "SerialParalelo_PhyRX.v:1" *)
module SerialParalelo_PhyRX_Synth(clk, clk_4f, serial, reset, paralelo, validOut, active);
  (* src = "SerialParalelo_PhyRX.v:37" *)
  wire _000_;
  (* src = "SerialParalelo_PhyRX.v:37" *)
  wire _001_;
  (* src = "SerialParalelo_PhyRX.v:37" *)
  wire _002_;
  (* src = "SerialParalelo_PhyRX.v:37" *)
  wire _003_;
  (* src = "SerialParalelo_PhyRX.v:37" *)
  wire _004_;
  (* src = "SerialParalelo_PhyRX.v:21" *)
  wire [3:0] _005_;
  (* src = "SerialParalelo_PhyRX.v:37" *)
  wire [7:0] _006_;
  (* src = "SerialParalelo_PhyRX.v:21" *)
  wire [7:0] _007_;
  (* src = "SerialParalelo_PhyRX.v:21" *)
  wire [7:0] _008_;
  (* src = "SerialParalelo_PhyRX.v:37" *)
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  (* init = 1'h0 *)
  (* src = "SerialParalelo_PhyRX.v:11" *)
  wire BC_counter;
  (* src = "SerialParalelo_PhyRX.v:8" *)
  output active;
  (* init = 1'h0 *)
  (* src = "SerialParalelo_PhyRX.v:17" *)
  wire aux1;
  (* init = 1'h0 *)
  (* src = "SerialParalelo_PhyRX.v:18" *)
  wire aux2;
  (* init = 1'h0 *)
  (* src = "SerialParalelo_PhyRX.v:19" *)
  wire aux3;
  (* src = "SerialParalelo_PhyRX.v:2" *)
  input clk;
  (* src = "SerialParalelo_PhyRX.v:3" *)
  input clk_4f;
  (* init = 8'h00 *)
  (* src = "SerialParalelo_PhyRX.v:16" *)
  wire [7:0] data2send;
  (* init = 4'h0 *)
  (* src = "SerialParalelo_PhyRX.v:12" *)
  wire [3:0] i;
  (* src = "SerialParalelo_PhyRX.v:6" *)
  output [7:0] paralelo;
  (* src = "SerialParalelo_PhyRX.v:5" *)
  input reset;
  (* src = "SerialParalelo_PhyRX.v:4" *)
  input serial;
  (* init = 8'h00 *)
  (* src = "SerialParalelo_PhyRX.v:13" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] temp;
  (* init = 8'h00 *)
  (* src = "SerialParalelo_PhyRX.v:14" *)
  wire [7:0] temp2;
  (* init = 8'h00 *)
  (* src = "SerialParalelo_PhyRX.v:15" *)
  wire [7:0] temp3;
  (* src = "SerialParalelo_PhyRX.v:7" *)
  output validOut;
  NOT _146_ (
    .A(temp2[6]),
    .Y(_120_)
  );
  NOT _147_ (
    .A(i[3]),
    .Y(_121_)
  );
  NOT _148_ (
    .A(i[0]),
    .Y(_122_)
  );
  NOT _149_ (
    .A(i[1]),
    .Y(_123_)
  );
  NOT _150_ (
    .A(i[2]),
    .Y(_124_)
  );
  NOT _151_ (
    .A(reset),
    .Y(_125_)
  );
  NOT _152_ (
    .A(temp2[1]),
    .Y(_126_)
  );
  NOT _153_ (
    .A(temp2[2]),
    .Y(_127_)
  );
  NOT _154_ (
    .A(temp2[3]),
    .Y(_128_)
  );
  NOT _155_ (
    .A(temp2[4]),
    .Y(_129_)
  );
  NOT _156_ (
    .A(temp2[5]),
    .Y(_130_)
  );
  NOT _157_ (
    .A(temp2[7]),
    .Y(_131_)
  );
  NAND _158_ (
    .A(temp2[3]),
    .B(temp2[4]),
    .Y(_132_)
  );
  NAND _159_ (
    .A(temp2[5]),
    .B(temp2[7]),
    .Y(_133_)
  );
  NOR _160_ (
    .A(_132_),
    .B(_133_),
    .Y(_134_)
  );
  NOT _161_ (
    .A(_134_),
    .Y(_135_)
  );
  NOR _162_ (
    .A(temp2[6]),
    .B(temp2[0]),
    .Y(_136_)
  );
  NOT _163_ (
    .A(_136_),
    .Y(_137_)
  );
  NOR _164_ (
    .A(temp2[1]),
    .B(_127_),
    .Y(_138_)
  );
  NAND _165_ (
    .A(_126_),
    .B(temp2[2]),
    .Y(_139_)
  );
  NOR _166_ (
    .A(_137_),
    .B(_139_),
    .Y(_140_)
  );
  NAND _167_ (
    .A(_136_),
    .B(_138_),
    .Y(_141_)
  );
  NOR _168_ (
    .A(_135_),
    .B(_141_),
    .Y(_142_)
  );
  NAND _169_ (
    .A(_134_),
    .B(_140_),
    .Y(_143_)
  );
  NOR _170_ (
    .A(_125_),
    .B(_143_),
    .Y(_002_)
  );
  NAND _171_ (
    .A(aux2),
    .B(_002_),
    .Y(_144_)
  );
  NOT _172_ (
    .A(_144_),
    .Y(_004_)
  );
  NAND _173_ (
    .A(aux1),
    .B(_002_),
    .Y(_145_)
  );
  NOT _174_ (
    .A(_145_),
    .Y(_003_)
  );
  NAND _175_ (
    .A(reset),
    .B(BC_counter),
    .Y(_010_)
  );
  NOT _176_ (
    .A(_010_),
    .Y(_001_)
  );
  NAND _177_ (
    .A(aux3),
    .B(_002_),
    .Y(_011_)
  );
  NAND _178_ (
    .A(_010_),
    .B(_011_),
    .Y(_000_)
  );
  NOR _179_ (
    .A(validOut),
    .B(active),
    .Y(_012_)
  );
  NOR _180_ (
    .A(_125_),
    .B(_142_),
    .Y(_013_)
  );
  NOT _181_ (
    .A(_013_),
    .Y(_014_)
  );
  NOR _182_ (
    .A(_012_),
    .B(_014_),
    .Y(_009_)
  );
  NAND _183_ (
    .A(reset),
    .B(temp2[0]),
    .Y(_015_)
  );
  NAND _184_ (
    .A(paralelo[0]),
    .B(_002_),
    .Y(_016_)
  );
  NAND _185_ (
    .A(_015_),
    .B(_016_),
    .Y(_006_[0])
  );
  NAND _186_ (
    .A(reset),
    .B(temp2[1]),
    .Y(_017_)
  );
  NAND _187_ (
    .A(paralelo[1]),
    .B(_002_),
    .Y(_018_)
  );
  NAND _188_ (
    .A(_017_),
    .B(_018_),
    .Y(_006_[1])
  );
  NOR _189_ (
    .A(paralelo[2]),
    .B(_143_),
    .Y(_019_)
  );
  NAND _190_ (
    .A(reset),
    .B(temp2[2]),
    .Y(_020_)
  );
  NOR _191_ (
    .A(_019_),
    .B(_020_),
    .Y(_006_[2])
  );
  NAND _192_ (
    .A(temp2[3]),
    .B(_013_),
    .Y(_021_)
  );
  NAND _193_ (
    .A(paralelo[3]),
    .B(_002_),
    .Y(_022_)
  );
  NAND _194_ (
    .A(_021_),
    .B(_022_),
    .Y(_006_[3])
  );
  NAND _195_ (
    .A(temp2[4]),
    .B(_013_),
    .Y(_023_)
  );
  NAND _196_ (
    .A(paralelo[4]),
    .B(_002_),
    .Y(_024_)
  );
  NAND _197_ (
    .A(_023_),
    .B(_024_),
    .Y(_006_[4])
  );
  NAND _198_ (
    .A(temp2[5]),
    .B(_013_),
    .Y(_025_)
  );
  NAND _199_ (
    .A(paralelo[5]),
    .B(_002_),
    .Y(_026_)
  );
  NAND _200_ (
    .A(_025_),
    .B(_026_),
    .Y(_006_[5])
  );
  NAND _201_ (
    .A(temp2[6]),
    .B(reset),
    .Y(_027_)
  );
  NAND _202_ (
    .A(paralelo[6]),
    .B(_002_),
    .Y(_028_)
  );
  NAND _203_ (
    .A(_027_),
    .B(_028_),
    .Y(_006_[6])
  );
  NAND _204_ (
    .A(temp2[7]),
    .B(_013_),
    .Y(_029_)
  );
  NAND _205_ (
    .A(paralelo[7]),
    .B(_002_),
    .Y(_030_)
  );
  NAND _206_ (
    .A(_029_),
    .B(_030_),
    .Y(_006_[7])
  );
  NAND _207_ (
    .A(i[0]),
    .B(i[1]),
    .Y(_031_)
  );
  NOT _208_ (
    .A(_031_),
    .Y(_032_)
  );
  NOR _209_ (
    .A(i[3]),
    .B(_124_),
    .Y(_033_)
  );
  NAND _210_ (
    .A(_121_),
    .B(i[2]),
    .Y(_034_)
  );
  NOR _211_ (
    .A(_031_),
    .B(_034_),
    .Y(_035_)
  );
  NAND _212_ (
    .A(_032_),
    .B(_033_),
    .Y(_036_)
  );
  NAND _213_ (
    .A(serial),
    .B(_035_),
    .Y(_037_)
  );
  NAND _214_ (
    .A(temp3[7]),
    .B(_036_),
    .Y(_038_)
  );
  NAND _215_ (
    .A(_037_),
    .B(_038_),
    .Y(_039_)
  );
  NAND _216_ (
    .A(reset),
    .B(_039_),
    .Y(_040_)
  );
  NOT _217_ (
    .A(_040_),
    .Y(_008_[7])
  );
  NOR _218_ (
    .A(_122_),
    .B(i[1]),
    .Y(_041_)
  );
  NAND _219_ (
    .A(i[0]),
    .B(_123_),
    .Y(_042_)
  );
  NOR _220_ (
    .A(_034_),
    .B(_042_),
    .Y(_043_)
  );
  NAND _221_ (
    .A(_033_),
    .B(_041_),
    .Y(_044_)
  );
  NAND _222_ (
    .A(serial),
    .B(_043_),
    .Y(_045_)
  );
  NAND _223_ (
    .A(temp3[5]),
    .B(_044_),
    .Y(_046_)
  );
  NAND _224_ (
    .A(_045_),
    .B(_046_),
    .Y(_047_)
  );
  NAND _225_ (
    .A(reset),
    .B(_047_),
    .Y(_048_)
  );
  NOT _226_ (
    .A(_048_),
    .Y(_008_[5])
  );
  NOR _227_ (
    .A(i[0]),
    .B(i[1]),
    .Y(_049_)
  );
  NOT _228_ (
    .A(_049_),
    .Y(_050_)
  );
  NOR _229_ (
    .A(_034_),
    .B(_050_),
    .Y(_051_)
  );
  NAND _230_ (
    .A(_033_),
    .B(_049_),
    .Y(_052_)
  );
  NAND _231_ (
    .A(serial),
    .B(_051_),
    .Y(_053_)
  );
  NAND _232_ (
    .A(temp3[4]),
    .B(_052_),
    .Y(_054_)
  );
  NAND _233_ (
    .A(_053_),
    .B(_054_),
    .Y(_055_)
  );
  NAND _234_ (
    .A(reset),
    .B(_055_),
    .Y(_056_)
  );
  NOT _235_ (
    .A(_056_),
    .Y(_008_[4])
  );
  NOR _236_ (
    .A(i[3]),
    .B(i[2]),
    .Y(_057_)
  );
  NAND _237_ (
    .A(_121_),
    .B(_124_),
    .Y(_058_)
  );
  NOR _238_ (
    .A(_031_),
    .B(_058_),
    .Y(_059_)
  );
  NAND _239_ (
    .A(_032_),
    .B(_057_),
    .Y(_060_)
  );
  NAND _240_ (
    .A(serial),
    .B(_059_),
    .Y(_061_)
  );
  NAND _241_ (
    .A(temp3[3]),
    .B(_060_),
    .Y(_062_)
  );
  NAND _242_ (
    .A(_061_),
    .B(_062_),
    .Y(_063_)
  );
  NAND _243_ (
    .A(reset),
    .B(_063_),
    .Y(_064_)
  );
  NOT _244_ (
    .A(_064_),
    .Y(_008_[3])
  );
  NOR _245_ (
    .A(i[0]),
    .B(_123_),
    .Y(_065_)
  );
  NAND _246_ (
    .A(_122_),
    .B(i[1]),
    .Y(_066_)
  );
  NOR _247_ (
    .A(_058_),
    .B(_066_),
    .Y(_067_)
  );
  NAND _248_ (
    .A(_057_),
    .B(_065_),
    .Y(_068_)
  );
  NAND _249_ (
    .A(serial),
    .B(_067_),
    .Y(_069_)
  );
  NAND _250_ (
    .A(temp3[2]),
    .B(_068_),
    .Y(_070_)
  );
  NAND _251_ (
    .A(_069_),
    .B(_070_),
    .Y(_071_)
  );
  NAND _252_ (
    .A(reset),
    .B(_071_),
    .Y(_072_)
  );
  NOT _253_ (
    .A(_072_),
    .Y(_008_[2])
  );
  NOR _254_ (
    .A(_042_),
    .B(_058_),
    .Y(_073_)
  );
  NAND _255_ (
    .A(_041_),
    .B(_057_),
    .Y(_074_)
  );
  NAND _256_ (
    .A(serial),
    .B(_073_),
    .Y(_075_)
  );
  NAND _257_ (
    .A(temp3[1]),
    .B(_074_),
    .Y(_076_)
  );
  NAND _258_ (
    .A(_075_),
    .B(_076_),
    .Y(_077_)
  );
  NAND _259_ (
    .A(reset),
    .B(_077_),
    .Y(_078_)
  );
  NOT _260_ (
    .A(_078_),
    .Y(_008_[1])
  );
  NAND _261_ (
    .A(_124_),
    .B(_049_),
    .Y(_079_)
  );
  NAND _262_ (
    .A(_049_),
    .B(_057_),
    .Y(_080_)
  );
  NOT _263_ (
    .A(_080_),
    .Y(_081_)
  );
  NAND _264_ (
    .A(temp3[0]),
    .B(_080_),
    .Y(_082_)
  );
  NAND _265_ (
    .A(serial),
    .B(_081_),
    .Y(_083_)
  );
  NAND _266_ (
    .A(_082_),
    .B(_083_),
    .Y(_084_)
  );
  NAND _267_ (
    .A(reset),
    .B(_084_),
    .Y(_085_)
  );
  NOT _268_ (
    .A(_085_),
    .Y(_008_[0])
  );
  NOR _269_ (
    .A(_034_),
    .B(_066_),
    .Y(_086_)
  );
  NAND _270_ (
    .A(_033_),
    .B(_065_),
    .Y(_087_)
  );
  NAND _271_ (
    .A(serial),
    .B(_086_),
    .Y(_088_)
  );
  NAND _272_ (
    .A(temp3[6]),
    .B(_087_),
    .Y(_089_)
  );
  NAND _273_ (
    .A(_088_),
    .B(_089_),
    .Y(_090_)
  );
  NAND _274_ (
    .A(reset),
    .B(_090_),
    .Y(_091_)
  );
  NOT _275_ (
    .A(_091_),
    .Y(_008_[6])
  );
  NAND _276_ (
    .A(temp2[0]),
    .B(_080_),
    .Y(_092_)
  );
  NAND _277_ (
    .A(_083_),
    .B(_092_),
    .Y(_093_)
  );
  NAND _278_ (
    .A(reset),
    .B(_093_),
    .Y(_094_)
  );
  NOT _279_ (
    .A(_094_),
    .Y(_007_[0])
  );
  NOR _280_ (
    .A(_077_),
    .B(_080_),
    .Y(_095_)
  );
  NAND _281_ (
    .A(_126_),
    .B(_080_),
    .Y(_096_)
  );
  NAND _282_ (
    .A(reset),
    .B(_096_),
    .Y(_097_)
  );
  NOR _283_ (
    .A(_095_),
    .B(_097_),
    .Y(_007_[1])
  );
  NOR _284_ (
    .A(_071_),
    .B(_080_),
    .Y(_098_)
  );
  NAND _285_ (
    .A(_127_),
    .B(_080_),
    .Y(_099_)
  );
  NAND _286_ (
    .A(reset),
    .B(_099_),
    .Y(_100_)
  );
  NOR _287_ (
    .A(_098_),
    .B(_100_),
    .Y(_007_[2])
  );
  NOR _288_ (
    .A(_063_),
    .B(_080_),
    .Y(_101_)
  );
  NAND _289_ (
    .A(_128_),
    .B(_080_),
    .Y(_102_)
  );
  NAND _290_ (
    .A(reset),
    .B(_102_),
    .Y(_103_)
  );
  NOR _291_ (
    .A(_101_),
    .B(_103_),
    .Y(_007_[3])
  );
  NOR _292_ (
    .A(_055_),
    .B(_080_),
    .Y(_104_)
  );
  NAND _293_ (
    .A(_129_),
    .B(_080_),
    .Y(_105_)
  );
  NAND _294_ (
    .A(reset),
    .B(_105_),
    .Y(_106_)
  );
  NOR _295_ (
    .A(_104_),
    .B(_106_),
    .Y(_007_[4])
  );
  NOR _296_ (
    .A(_047_),
    .B(_080_),
    .Y(_107_)
  );
  NAND _297_ (
    .A(_130_),
    .B(_080_),
    .Y(_108_)
  );
  NAND _298_ (
    .A(reset),
    .B(_108_),
    .Y(_109_)
  );
  NOR _299_ (
    .A(_107_),
    .B(_109_),
    .Y(_007_[5])
  );
  NOR _300_ (
    .A(_080_),
    .B(_090_),
    .Y(_110_)
  );
  NAND _301_ (
    .A(_120_),
    .B(_080_),
    .Y(_111_)
  );
  NAND _302_ (
    .A(reset),
    .B(_111_),
    .Y(_112_)
  );
  NOR _303_ (
    .A(_110_),
    .B(_112_),
    .Y(_007_[6])
  );
  NOR _304_ (
    .A(_039_),
    .B(_080_),
    .Y(_113_)
  );
  NAND _305_ (
    .A(_131_),
    .B(_080_),
    .Y(_114_)
  );
  NAND _306_ (
    .A(reset),
    .B(_114_),
    .Y(_115_)
  );
  NOR _307_ (
    .A(_113_),
    .B(_115_),
    .Y(_007_[7])
  );
  NAND _308_ (
    .A(i[0]),
    .B(reset),
    .Y(_005_[0])
  );
  NOR _309_ (
    .A(_125_),
    .B(_049_),
    .Y(_116_)
  );
  NAND _310_ (
    .A(_031_),
    .B(_116_),
    .Y(_005_[1])
  );
  NAND _311_ (
    .A(i[2]),
    .B(_050_),
    .Y(_117_)
  );
  NAND _312_ (
    .A(reset),
    .B(_079_),
    .Y(_118_)
  );
  NOT _313_ (
    .A(_118_),
    .Y(_119_)
  );
  NAND _314_ (
    .A(_117_),
    .B(_119_),
    .Y(_005_[2])
  );
  NOR _315_ (
    .A(_121_),
    .B(_118_),
    .Y(_005_[3])
  );
  (* src = "SerialParalelo_PhyRX.v:37" *)
  DFF _316_ (
    .C(clk_4f),
    .D(_006_[0]),
    .Q(paralelo[0])
  );
  (* src = "SerialParalelo_PhyRX.v:37" *)
  DFF _317_ (
    .C(clk_4f),
    .D(_006_[1]),
    .Q(paralelo[1])
  );
  (* src = "SerialParalelo_PhyRX.v:37" *)
  DFF _318_ (
    .C(clk_4f),
    .D(_006_[2]),
    .Q(paralelo[2])
  );
  (* src = "SerialParalelo_PhyRX.v:37" *)
  DFF _319_ (
    .C(clk_4f),
    .D(_006_[3]),
    .Q(paralelo[3])
  );
  (* src = "SerialParalelo_PhyRX.v:37" *)
  DFF _320_ (
    .C(clk_4f),
    .D(_006_[4]),
    .Q(paralelo[4])
  );
  (* src = "SerialParalelo_PhyRX.v:37" *)
  DFF _321_ (
    .C(clk_4f),
    .D(_006_[5]),
    .Q(paralelo[5])
  );
  (* src = "SerialParalelo_PhyRX.v:37" *)
  DFF _322_ (
    .C(clk_4f),
    .D(_006_[6]),
    .Q(paralelo[6])
  );
  (* src = "SerialParalelo_PhyRX.v:37" *)
  DFF _323_ (
    .C(clk_4f),
    .D(_006_[7]),
    .Q(paralelo[7])
  );
  (* src = "SerialParalelo_PhyRX.v:37" *)
  DFF _324_ (
    .C(clk_4f),
    .D(_009_),
    .Q(validOut)
  );
  (* src = "SerialParalelo_PhyRX.v:37" *)
  DFF _325_ (
    .C(clk_4f),
    .D(_001_),
    .Q(active)
  );
  (* src = "SerialParalelo_PhyRX.v:37" *)
  DFF _326_ (
    .C(clk_4f),
    .D(_000_),
    .Q(BC_counter)
  );
  (* src = "SerialParalelo_PhyRX.v:37" *)
  DFF _327_ (
    .C(clk_4f),
    .D(_002_),
    .Q(aux1)
  );
  (* src = "SerialParalelo_PhyRX.v:37" *)
  DFF _328_ (
    .C(clk_4f),
    .D(_003_),
    .Q(aux2)
  );
  (* src = "SerialParalelo_PhyRX.v:37" *)
  DFF _329_ (
    .C(clk_4f),
    .D(_004_),
    .Q(aux3)
  );
  (* src = "SerialParalelo_PhyRX.v:21" *)
  DFF _330_ (
    .C(clk),
    .D(_005_[0]),
    .Q(i[0])
  );
  (* src = "SerialParalelo_PhyRX.v:21" *)
  DFF _331_ (
    .C(clk),
    .D(_005_[1]),
    .Q(i[1])
  );
  (* src = "SerialParalelo_PhyRX.v:21" *)
  DFF _332_ (
    .C(clk),
    .D(_005_[2]),
    .Q(i[2])
  );
  (* src = "SerialParalelo_PhyRX.v:21" *)
  DFF _333_ (
    .C(clk),
    .D(_005_[3]),
    .Q(i[3])
  );
  (* src = "SerialParalelo_PhyRX.v:21" *)
  DFF _334_ (
    .C(clk),
    .D(_007_[0]),
    .Q(temp2[0])
  );
  (* src = "SerialParalelo_PhyRX.v:21" *)
  DFF _335_ (
    .C(clk),
    .D(_007_[1]),
    .Q(temp2[1])
  );
  (* src = "SerialParalelo_PhyRX.v:21" *)
  DFF _336_ (
    .C(clk),
    .D(_007_[2]),
    .Q(temp2[2])
  );
  (* src = "SerialParalelo_PhyRX.v:21" *)
  DFF _337_ (
    .C(clk),
    .D(_007_[3]),
    .Q(temp2[3])
  );
  (* src = "SerialParalelo_PhyRX.v:21" *)
  DFF _338_ (
    .C(clk),
    .D(_007_[4]),
    .Q(temp2[4])
  );
  (* src = "SerialParalelo_PhyRX.v:21" *)
  DFF _339_ (
    .C(clk),
    .D(_007_[5]),
    .Q(temp2[5])
  );
  (* src = "SerialParalelo_PhyRX.v:21" *)
  DFF _340_ (
    .C(clk),
    .D(_007_[6]),
    .Q(temp2[6])
  );
  (* src = "SerialParalelo_PhyRX.v:21" *)
  DFF _341_ (
    .C(clk),
    .D(_007_[7]),
    .Q(temp2[7])
  );
  (* src = "SerialParalelo_PhyRX.v:21" *)
  DFF _342_ (
    .C(clk),
    .D(_008_[0]),
    .Q(temp3[0])
  );
  (* src = "SerialParalelo_PhyRX.v:21" *)
  DFF _343_ (
    .C(clk),
    .D(_008_[1]),
    .Q(temp3[1])
  );
  (* src = "SerialParalelo_PhyRX.v:21" *)
  DFF _344_ (
    .C(clk),
    .D(_008_[2]),
    .Q(temp3[2])
  );
  (* src = "SerialParalelo_PhyRX.v:21" *)
  DFF _345_ (
    .C(clk),
    .D(_008_[3]),
    .Q(temp3[3])
  );
  (* src = "SerialParalelo_PhyRX.v:21" *)
  DFF _346_ (
    .C(clk),
    .D(_008_[4]),
    .Q(temp3[4])
  );
  (* src = "SerialParalelo_PhyRX.v:21" *)
  DFF _347_ (
    .C(clk),
    .D(_008_[5]),
    .Q(temp3[5])
  );
  (* src = "SerialParalelo_PhyRX.v:21" *)
  DFF _348_ (
    .C(clk),
    .D(_008_[6]),
    .Q(temp3[6])
  );
  (* src = "SerialParalelo_PhyRX.v:21" *)
  DFF _349_ (
    .C(clk),
    .D(_008_[7]),
    .Q(temp3[7])
  );
  assign data2send = temp2;
endmodule
