/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* src = "DeMux2x1.v:1" *)
module DeMux2x1x(dataOut0, dataOut1, validOut0, validOut1, dataIn, validIn, selector, clk, reset);
  (* src = "DeMux2x1.v:36" *)
  wire [7:0] _000_;
  (* src = "DeMux2x1.v:52" *)
  wire [7:0] _001_;
  (* src = "DeMux2x1.v:36" *)
  wire _002_;
  (* src = "DeMux2x1.v:52" *)
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  (* src = "DeMux2x1.v:9" *)
  input clk;
  (* src = "DeMux2x1.v:6" *)
  input [7:0] dataIn;
  (* src = "DeMux2x1.v:2" *)
  output [7:0] dataOut0;
  (* src = "DeMux2x1.v:3" *)
  output [7:0] dataOut1;
  (* src = "DeMux2x1.v:10" *)
  input reset;
  (* src = "DeMux2x1.v:8" *)
  input selector;
  (* src = "DeMux2x1.v:7" *)
  input validIn;
  (* src = "DeMux2x1.v:4" *)
  output validOut0;
  (* src = "DeMux2x1.v:5" *)
  output validOut1;
  NOT _070_ (
    .A(validIn),
    .Y(_027_)
  );
  NOT _071_ (
    .A(selector),
    .Y(_028_)
  );
  NOT _072_ (
    .A(dataIn[0]),
    .Y(_029_)
  );
  NOT _073_ (
    .A(dataIn[1]),
    .Y(_030_)
  );
  NOT _074_ (
    .A(dataIn[2]),
    .Y(_031_)
  );
  NOT _075_ (
    .A(dataIn[3]),
    .Y(_032_)
  );
  NOT _076_ (
    .A(dataIn[4]),
    .Y(_033_)
  );
  NOT _077_ (
    .A(dataIn[5]),
    .Y(_034_)
  );
  NOT _078_ (
    .A(dataIn[6]),
    .Y(_035_)
  );
  NOT _079_ (
    .A(dataIn[7]),
    .Y(_036_)
  );
  NOR _080_ (
    .A(_027_),
    .B(_028_),
    .Y(_037_)
  );
  NAND _081_ (
    .A(_029_),
    .B(_037_),
    .Y(_038_)
  );
  NAND _082_ (
    .A(reset),
    .B(selector),
    .Y(_039_)
  );
  NAND _083_ (
    .A(reset),
    .B(_037_),
    .Y(_040_)
  );
  NOR _084_ (
    .A(dataOut1[0]),
    .B(_037_),
    .Y(_041_)
  );
  NAND _085_ (
    .A(reset),
    .B(_038_),
    .Y(_042_)
  );
  NOR _086_ (
    .A(_041_),
    .B(_042_),
    .Y(_001_[0])
  );
  NAND _087_ (
    .A(_030_),
    .B(_037_),
    .Y(_043_)
  );
  NOR _088_ (
    .A(dataOut1[1]),
    .B(_037_),
    .Y(_044_)
  );
  NAND _089_ (
    .A(reset),
    .B(_043_),
    .Y(_045_)
  );
  NOR _090_ (
    .A(_044_),
    .B(_045_),
    .Y(_001_[1])
  );
  NAND _091_ (
    .A(_031_),
    .B(_037_),
    .Y(_046_)
  );
  NOR _092_ (
    .A(dataOut1[2]),
    .B(_037_),
    .Y(_047_)
  );
  NAND _093_ (
    .A(reset),
    .B(_046_),
    .Y(_048_)
  );
  NOR _094_ (
    .A(_047_),
    .B(_048_),
    .Y(_001_[2])
  );
  NAND _095_ (
    .A(_032_),
    .B(_037_),
    .Y(_049_)
  );
  NOR _096_ (
    .A(dataOut1[3]),
    .B(_037_),
    .Y(_050_)
  );
  NAND _097_ (
    .A(reset),
    .B(_049_),
    .Y(_051_)
  );
  NOR _098_ (
    .A(_050_),
    .B(_051_),
    .Y(_001_[3])
  );
  NAND _099_ (
    .A(_033_),
    .B(_037_),
    .Y(_052_)
  );
  NOR _100_ (
    .A(dataOut1[4]),
    .B(_037_),
    .Y(_053_)
  );
  NAND _101_ (
    .A(reset),
    .B(_052_),
    .Y(_054_)
  );
  NOR _102_ (
    .A(_053_),
    .B(_054_),
    .Y(_001_[4])
  );
  NAND _103_ (
    .A(_034_),
    .B(_037_),
    .Y(_055_)
  );
  NOR _104_ (
    .A(dataOut1[5]),
    .B(_037_),
    .Y(_056_)
  );
  NAND _105_ (
    .A(reset),
    .B(_055_),
    .Y(_057_)
  );
  NOR _106_ (
    .A(_056_),
    .B(_057_),
    .Y(_001_[5])
  );
  NAND _107_ (
    .A(_035_),
    .B(_037_),
    .Y(_058_)
  );
  NOR _108_ (
    .A(dataOut1[6]),
    .B(_037_),
    .Y(_059_)
  );
  NAND _109_ (
    .A(reset),
    .B(_058_),
    .Y(_060_)
  );
  NOR _110_ (
    .A(_059_),
    .B(_060_),
    .Y(_001_[6])
  );
  NAND _111_ (
    .A(_036_),
    .B(_037_),
    .Y(_061_)
  );
  NOR _112_ (
    .A(dataOut1[7]),
    .B(_037_),
    .Y(_062_)
  );
  NAND _113_ (
    .A(reset),
    .B(_061_),
    .Y(_063_)
  );
  NOR _114_ (
    .A(_062_),
    .B(_063_),
    .Y(_001_[7])
  );
  NOR _115_ (
    .A(_027_),
    .B(selector),
    .Y(_064_)
  );
  NAND _116_ (
    .A(reset),
    .B(_064_),
    .Y(_065_)
  );
  NAND _117_ (
    .A(reset),
    .B(_028_),
    .Y(_066_)
  );
  NAND _118_ (
    .A(validOut0),
    .B(_066_),
    .Y(_067_)
  );
  NAND _119_ (
    .A(_065_),
    .B(_067_),
    .Y(_002_)
  );
  NOR _120_ (
    .A(dataOut0[0]),
    .B(_064_),
    .Y(_068_)
  );
  NAND _121_ (
    .A(_029_),
    .B(_064_),
    .Y(_069_)
  );
  NAND _122_ (
    .A(reset),
    .B(_069_),
    .Y(_004_)
  );
  NOR _123_ (
    .A(_068_),
    .B(_004_),
    .Y(_000_[0])
  );
  NOR _124_ (
    .A(dataOut0[1]),
    .B(_064_),
    .Y(_005_)
  );
  NAND _125_ (
    .A(_030_),
    .B(_064_),
    .Y(_006_)
  );
  NAND _126_ (
    .A(reset),
    .B(_006_),
    .Y(_007_)
  );
  NOR _127_ (
    .A(_005_),
    .B(_007_),
    .Y(_000_[1])
  );
  NOR _128_ (
    .A(dataOut0[2]),
    .B(_064_),
    .Y(_008_)
  );
  NAND _129_ (
    .A(_031_),
    .B(_064_),
    .Y(_009_)
  );
  NAND _130_ (
    .A(reset),
    .B(_009_),
    .Y(_010_)
  );
  NOR _131_ (
    .A(_008_),
    .B(_010_),
    .Y(_000_[2])
  );
  NOR _132_ (
    .A(dataOut0[3]),
    .B(_064_),
    .Y(_011_)
  );
  NAND _133_ (
    .A(_032_),
    .B(_064_),
    .Y(_012_)
  );
  NAND _134_ (
    .A(reset),
    .B(_012_),
    .Y(_013_)
  );
  NOR _135_ (
    .A(_011_),
    .B(_013_),
    .Y(_000_[3])
  );
  NOR _136_ (
    .A(dataOut0[4]),
    .B(_064_),
    .Y(_014_)
  );
  NAND _137_ (
    .A(_033_),
    .B(_064_),
    .Y(_015_)
  );
  NAND _138_ (
    .A(reset),
    .B(_015_),
    .Y(_016_)
  );
  NOR _139_ (
    .A(_014_),
    .B(_016_),
    .Y(_000_[4])
  );
  NOR _140_ (
    .A(dataOut0[5]),
    .B(_064_),
    .Y(_017_)
  );
  NAND _141_ (
    .A(_034_),
    .B(_064_),
    .Y(_018_)
  );
  NAND _142_ (
    .A(reset),
    .B(_018_),
    .Y(_019_)
  );
  NOR _143_ (
    .A(_017_),
    .B(_019_),
    .Y(_000_[5])
  );
  NOR _144_ (
    .A(dataOut0[6]),
    .B(_064_),
    .Y(_020_)
  );
  NAND _145_ (
    .A(_035_),
    .B(_064_),
    .Y(_021_)
  );
  NAND _146_ (
    .A(reset),
    .B(_021_),
    .Y(_022_)
  );
  NOR _147_ (
    .A(_020_),
    .B(_022_),
    .Y(_000_[6])
  );
  NOR _148_ (
    .A(dataOut0[7]),
    .B(_064_),
    .Y(_023_)
  );
  NAND _149_ (
    .A(_036_),
    .B(_064_),
    .Y(_024_)
  );
  NAND _150_ (
    .A(reset),
    .B(_024_),
    .Y(_025_)
  );
  NOR _151_ (
    .A(_023_),
    .B(_025_),
    .Y(_000_[7])
  );
  NAND _152_ (
    .A(validOut1),
    .B(_039_),
    .Y(_026_)
  );
  NAND _153_ (
    .A(_040_),
    .B(_026_),
    .Y(_003_)
  );
  (* src = "DeMux2x1.v:52" *)
  DFF _154_ (
    .C(clk),
    .D(_001_[0]),
    .Q(dataOut1[0])
  );
  (* src = "DeMux2x1.v:52" *)
  DFF _155_ (
    .C(clk),
    .D(_001_[1]),
    .Q(dataOut1[1])
  );
  (* src = "DeMux2x1.v:52" *)
  DFF _156_ (
    .C(clk),
    .D(_001_[2]),
    .Q(dataOut1[2])
  );
  (* src = "DeMux2x1.v:52" *)
  DFF _157_ (
    .C(clk),
    .D(_001_[3]),
    .Q(dataOut1[3])
  );
  (* src = "DeMux2x1.v:52" *)
  DFF _158_ (
    .C(clk),
    .D(_001_[4]),
    .Q(dataOut1[4])
  );
  (* src = "DeMux2x1.v:52" *)
  DFF _159_ (
    .C(clk),
    .D(_001_[5]),
    .Q(dataOut1[5])
  );
  (* src = "DeMux2x1.v:52" *)
  DFF _160_ (
    .C(clk),
    .D(_001_[6]),
    .Q(dataOut1[6])
  );
  (* src = "DeMux2x1.v:52" *)
  DFF _161_ (
    .C(clk),
    .D(_001_[7]),
    .Q(dataOut1[7])
  );
  (* src = "DeMux2x1.v:52" *)
  DFF _162_ (
    .C(clk),
    .D(_003_),
    .Q(validOut1)
  );
  (* src = "DeMux2x1.v:36" *)
  DFF _163_ (
    .C(clk),
    .D(_000_[0]),
    .Q(dataOut0[0])
  );
  (* src = "DeMux2x1.v:36" *)
  DFF _164_ (
    .C(clk),
    .D(_000_[1]),
    .Q(dataOut0[1])
  );
  (* src = "DeMux2x1.v:36" *)
  DFF _165_ (
    .C(clk),
    .D(_000_[2]),
    .Q(dataOut0[2])
  );
  (* src = "DeMux2x1.v:36" *)
  DFF _166_ (
    .C(clk),
    .D(_000_[3]),
    .Q(dataOut0[3])
  );
  (* src = "DeMux2x1.v:36" *)
  DFF _167_ (
    .C(clk),
    .D(_000_[4]),
    .Q(dataOut0[4])
  );
  (* src = "DeMux2x1.v:36" *)
  DFF _168_ (
    .C(clk),
    .D(_000_[5]),
    .Q(dataOut0[5])
  );
  (* src = "DeMux2x1.v:36" *)
  DFF _169_ (
    .C(clk),
    .D(_000_[6]),
    .Q(dataOut0[6])
  );
  (* src = "DeMux2x1.v:36" *)
  DFF _170_ (
    .C(clk),
    .D(_000_[7]),
    .Q(dataOut0[7])
  );
  (* src = "DeMux2x1.v:36" *)
  DFF _171_ (
    .C(clk),
    .D(_002_),
    .Q(validOut0)
  );
endmodule

(* top =  1  *)
(* src = "demux_L2_synth.v:2" *)
module demux_L2_synth(dataOut0, dataOut1, validOut0, validOut1, dataIn, validIn, selector, clk, reset);
  (* src = "demux_L2_synth.v:10" *)
  input clk;
  (* src = "demux_L2_synth.v:7" *)
  input [7:0] dataIn;
  (* src = "demux_L2_synth.v:3" *)
  output [7:0] dataOut0;
  (* src = "demux_L2_synth.v:4" *)
  output [7:0] dataOut1;
  (* src = "demux_L2_synth.v:11" *)
  input reset;
  (* src = "demux_L2_synth.v:9" *)
  input selector;
  (* src = "demux_L2_synth.v:8" *)
  input validIn;
  (* src = "demux_L2_synth.v:5" *)
  output validOut0;
  (* src = "demux_L2_synth.v:6" *)
  output validOut1;
  (* module_not_derived = 32'd1 *)
  (* src = "demux_L2_synth.v:13" *)
  DeMux2x1 Demux (
    .clk(clk),
    .dataIn(dataIn),
    .dataOut0(dataOut0),
    .dataOut1(dataOut1),
    .reset(reset),
    .selector(selector),
    .validIn(validIn),
    .validOut0(validOut0),
    .validOut1(validOut1)
  );
endmodule
